### ISSUE TITLE
output calculation progress in mc somehow

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#100]

**Comment by egull** [comment]
I really don't know how to do this in a general way. We have fraction_completed that one could query in principle, and I would use that one and adapt it for each case. I propose not to do something here. @galexv ?

**Comment by galexv** [comment]
I agree that `mcmpiadapter<simclass>::fraction_completed()` is good enough for the purpose. Later we may want to make a short tutorial on how to use it to output the progress, if it makes sense. Let's close it now.
