### ISSUE TITLE
More intelligible type mismatch error messages in alps::params

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#101]
E.g.,

     alps::params p(argc, argv);
     p.define<int>("intp","Int parameter");
     p["intp"]=34.125;

causes an exception with error message which is not possible to decipher without `c++filt -t`.

**Comment by aeantipov** [comment]
Here's one other <pre>
 p.define<size_t>("sizetp","size_t parameter");
 p["sizetp"]=34;</pre>

**Comment by galexv** [comment]
Addressed by commits 73cc851, 2b61df3, 4b66e57.
