### ISSUE TITLE
alps::params support for vector of strings

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#103]

**Comment by galexv** [comment]
The biggest problem here is parsing the list of strings on input. E.g., commas and spaces inside quotes should not act as separators, etc. Or we have to say that "fancy strings in the lists are not supported".

**Comment by egull** [comment]
I think I would just not support this. Whatever you do, it's a mess.

**Comment by egull** [comment]
Will be dealt with in #195
