### ISSUE TITLE
disable parameter input from command line

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#104]
Feature request. Example : I have a parameter of type int, which is used in the code. In fact it's an enum, so I provide string as a command line interface option and I want that internal parameter to be hidden.

**Comment by galexv** [comment]
In what sense "hidden"? Not printed by `std::cout << p`? Or hidden from the help message?

**Comment by egull** [comment]
Andrey, this one needs a bit more of an explanation. Could you please elaborate?

**Comment by aeantipov** [comment]
Sorry, told it to Alex, but didn't write here. I won't to have the parameter, that is "defined", but hidden from the command line. It is used internally in some pieces of code, so I need a default value. However, it is set by other combination of parameters and therefore should not be set manually.

**Comment by galexv** [comment]
> Defining it with p["param"] = value in define_parameters is not a good option,
> cause it will override the value if it's already there.

But if the value is already there (e.g. by assignment) `define()` will fail anyway.
I suggest using something like:

     if  (!p["param"].is_already_there()) { p["param"]=value; }

only `is_already_there()` should be named more appropriately, like `defined()`, maybe?

**Comment by aeantipov** [comment]
That will do, I agree.

**Comment by galexv** [comment]
One more thought.
Hidden parameter may make sense if the parameter must be settable from the command line, but should not appear in the help message. But, as i now understand, the idea is that the parameter should not be even settable from the command line, right?

**Comment by aeantipov** [comment]
It might not be prohibited to be set from the command line, I.e. one might need it for debug. But end user better not see it
Sent using CloudMagic
On Wed, Apr 01, 2015 at 11:35 AM, Alexander Gaenko <notifications@github.com> wrote:One more thought.
Hidden parameter may make sense if the parameter must be settable from the command line, but should not appear in the help message. But, as i now understand, the idea is that the parameter should not be even settable from the command line, right?

**Comment by galexv** [comment]
If the "hidden" parameter is not required to be settable from a command line, this will work:

```C++
void define_params(alps::params& p)
{
   BOOST_ASSERT_MSG(!p.defined("hidden_int"), "hidden_int should not be already define()-d"); 
   if (!p.exists("hidden_int"))  p["hidden_int"]=42; // Setting "42" as default
   // ... defining other parameters ...
}
```

**Comment by egull** [comment]
Will be dealt with in #195

**Comment by galexv** [comment]
The [workaround suggested above](https://github.com/ALPSCore/ALPSCore/issues/104#issuecomment-105624618) is acceptable, i am closing this for now. If demand for this feature wil lbe high, we can always reopen.
