### ISSUE TITLE
Citable code

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#108]
Alex,
could you please have a look at the citable code https://guides.github.com/activities/citable-code/ and see if that is something we could get up and running by Friday (submission date of a paper that uses ALPSCore)?

**Comment by galexv** [comment]
Yes, sure. Basically, one needs a release, a description, and a license.

**Comment by egull** [comment]
Cool. So if we finalize out 0.3, we can cite it!

**Comment by galexv** [comment]
Zenodo (https://zenodo.org/account/settings/github/) sees my own repository, but does not see any of the organizations. Could you please try to login to Zenodo with your Github credentials? (The button "Sign in with Github" on the webpage)

**Comment by egull** [comment]
I'm having the same problem: I could access a public repository that I created for myself, but organisatorial repos are not visible. I'm stuck...

**Comment by aeantipov** [comment]
Same for me. "upload" option though can help here.

**Comment by galexv** [comment]
Upload is an option, or maybe cloning the release to a personal repo and using it with Zenodo. I guess it just takes a snapshot from the repo anyway.

**Comment by egull** [comment]
Zenodo started to work: I can now see ALPSCore in my zenodo, and I can see the webhook under stettings. I think we can generate a DOI with the next release.

**Comment by egull** [comment]
and it worked!

https://dx.doi.org/10.5281/zenodo.16616

https://zenodo.org/badge/11563/ALPSCore/ALPSCore.svg

The dx.doi.org link doesn't work yet, but I think that's a matter of time.

**Comment by aeantipov** [comment]
Hm, I see the badge disabled for ALPSCore.

**Comment by egull** [comment]
no. Took some time to get activated, but now it works.
