### ISSUE TITLE
Check if a parameter is set to its default

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#109]
We have `defined()` which tests if the parameter is set at all (thanks Andrey!). It would be good to have `p.is_default(name)` to check whether the option `name` is actually supplied or just acquired a default value.

**Comment by aeantipov** [comment]
Choose between `p["name"].is_default()/defaulted()` and `p.is_default(name)/defaulted(name)` . A straightforward choice seems to be the second one, cause `p["name"]` will give an exception if it's not defined. On the other hand, this might be ok (exceptions are good), as 'default' is defined within param value and not param

**Comment by galexv** [comment]
Actually, for the record, `p["no_such_param"]` by itself will not throw an exception: it will return a value of type `None`, which will throw an exception on assignment. So, if we specify `defined(name)==true` as "access to `name` will not throw", then the `defined()` method has to be modified a little. Otherwise code like this:

    alps::params p; 
    p["no_such_param"];
    int x;
    if (p.defined("no_such_param"))    x=p["no_such_param"];

will unexpectedly throw... At least i think so. :)

Btw, how to name the method? `defaulted()` or `is_default()`? Any opinions?

**Comment by aeantipov** [comment]
`defaulted()` has 1 less symbol to type and doesn't require shift button, so it would be my choice :+1:

**Comment by galexv** [comment]
Sounds reasonable. :)

**Comment by aeantipov** [comment]
actually it's also used in boost::program_options (see http://www.boost.org/doc/libs/1_54_0/boost/program_options/variables_map.hpp), so probably it is indeed a better choice

**Comment by galexv** [comment]
Should we change the name `defined()` to `exists()`?
Because a parameter can be "defined", that is, `define(name,....)` has been called. But it does not have a value and attempt to assign to/from it will throw. 

The `defined()` might be used to determine if the parameter was ever `define()`-ed, explicitly or implicitly (that is, by assignment) &mdash; but is this method needed?

**Comment by galexv** [comment]
Commit 9b2218 improves  `defined()`, commit bbd085 introduces `defaulted()`. Closing this feature request  as "implemented". (If it does not work, we can always open a bug issue. :) )
