### ISSUE TITLE
python libs should go into lib, not python: macports balks

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#112]
the ALPS python libs are currently installed into python. They should be put into lib instead (or some other place).
Reason: Macport refuses to install into python, it does not follow its directory structure.
Also: potentially better names, like alps_api_c.so rather than api_c.so?

**Comment by aeantipov** [comment]
it's tricky - it should probably go to `lib/python${python_version}/site-packages/` but ALPSCore packages are strictly speaking not python packages yet (there's no egg-info files)

**Comment by aeantipov** [comment]
resolved that the -DEnablePython=OFF is a choice for Macports.

**Comment by egull** [comment]
ok. I've done this and I've submitted the macports file to the repo. Let's see if they take it.
