### ISSUE TITLE
Linking error with alpscore and boost

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#117]
When I link my code with alpscore and boost (both compiled as static libs) I get an error of ` multiple definition of boost::program_options::validate`:
<pre>/work/03020/aantipov/modules/boost-cxx11/1.55.0/lib/libboost_program_options.a(value_semantic.cpp.o): In function `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)':
/work/03020/aantipov/code/boost_1_55_0/libs/program_options/src/value_semantic.cpp:(.text+0x5210): multiple definition of `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
/work/03020/aantipov/modules/alpscore/mpi/lib/libalps-params.a(params.cpp.o):/work/03020/aantipov/code/alpscore/params/src/params.cpp:(.text+0x0): first defined here</pre>
This comes from `boost::program_options::validate` override defined in `alps/params.hpp`
The order of linking the libraries does not matter.

**Comment by galexv** [comment]
It must be fixed now, by commit a217c99. I am closing it now, feel free to reopen if there are still problems.

**Comment by aeantipov** [comment]
Thanks!
