### ISSUE TITLE
Verify Boost version during cmake run and issue a proper message

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#120]
Verify `Boost_VERSION` or maybe request the minimum version using `find_package(boost 1.54 ....)`. This should be easy. Alternatively, we can try to run tests to verify that the required boost features are in place and working, but it would be much harder.

**Comment by egull** [comment]
Indeed. I've put the line into the CommonModuleDefinitions and tested it on my mac. If your boost is too old (I artificially required 1.59 to test) it now complains as:

CMake Error at /opt/local/share/cmake-3.2/Modules/FindBoost.cmake:1182 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /opt/local/include

  Detected version of Boost is too old.  Requested version was 1.59 (or
  newer).
