### ISSUE TITLE
Put Python modules in a separate package

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#121]
...and have them unit-tested (issue #43).

*Rationale*: The Python part has quite different build system; some special cases in common CMake macros/functions are specifically to accommodate the Python part.

**Comment by egull** [comment]
FYI as suspected this just got more urgent.

**Comment by aeantipov** [comment]
A possible solution from @dolfim : https://pybind11.readthedocs.org/en/latest/cmake.html 
Pros: does not require linking to python!!!

**Comment by galexv** [comment]
The Python cod is moved to a separate package [ALPSCore-Python](https://github.com/ALPSCore/ALPSCore-Python). 

PyBind is an interesting thing, maybe we can relax C++11 policy for ALPSCore-Python package?

I am closing this issue, redirecting the discussion to ALPSCore/ALPSCore-Python#3.
