### ISSUE TITLE
Improve alps::params::help_requested() : e.g., running a program without arguments

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#124]
When a program that uses `alps::params` is run without required arguments, the error message is not helpful. Add a way to easily detect the situation.

**Comment by dolfim** [comment]
Do you mean something like that?
```
Caught exception: Option 'BETA': Attempt to use uninitialized option value
```

I just got this error, and I thought that printing the help message when this kind of errors occur could be useful. I thin that Python argsparse is doing it.

**Comment by galexv** [comment]
Yes, that is it. However, we cannot just print the help message (we do not have an output stream at hand). Maybe make the help a part of the exception message? The uncaught exception will likely be printed.

However, what if i mistakenly code `double beta=p["BETTA"]` rather than `"BETA"`? The help message might mislead: the problem is not with the program arguments. 

I was thinking that `help_requested()` may just scan over all `define()`-d parameters and check whether any required one is missing.

**Comment by galexv** [comment]
Parameters implementation need some cleanup and a bit of a redesign; this issue will be addressed along the way.

**Comment by egull** [comment]
Will be dealt with in #195
