### ISSUE TITLE
Macports: ALPSCore fails on Snow Leopard

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#127]
ALPSCore fails on Snow Leopard

https://build.macports.org/builders/buildports-snowleopard-x86_64/builds/35425

Comment (by mojca@…):

The package fails to compile on [https://build.macports.org/builders
/buildports-snowleopard-x86_64/builds/35425 Snow Leopard].

{{{
/path/to/ALPSCore-0.4/accumulators/include/alps/accumulators/feature.hpp:47:
error: no match for ‘operator+’ in ‘std::vector<float,
std::allocator<float> >(((const std::allocator<float>&)((const
std::allocator<float>*)(& std::allocator<float>())))) +
alps::accumulators::impl::Result<std::vector<float, std::allocator<float>
, alps::accumulators::mean_tag,
alps::accumulators::impl::Result<std::vector<float, std::allocator<float>
, alps::accumulators::count_tag,
alps::accumulators::impl::ResultBase<std::vector<float,
std::allocator<float> > > > >()’
}}}

Most likely some appropriate compiler blacklist would solve the issue.

-- 
Ticket URL: <https://trac.macports.org/ticket/47350#comment:5>
MacPorts <https://www.macports.org/>
Ports system for OS X

**Comment by egull** [comment]
OK, suspicion is that this is a gcc 4.2 problem, but we officially allow gcc 4.2 (see prereqs). @galexv : should we fix this or should we up our requirements to 4.3 for gcc?

**Comment by aeantipov** [comment]
One thing to think about : 4.2 is default on macos <= 10.7, see https://trac.macports.org/wiki/UsingTheRightCompiler <https://trac.macports.org/wiki/UsingTheRightCompiler>

**Comment by galexv** [comment]
I will try to fix it to work with gcc 4.2. (The error message suggests that there is some name look-up problem).

**Comment by galexv** [comment]
...or maybe better to support 4.3+ only. (Needs testing with 4.3)

**Comment by egull** [comment]
...seems 4.2.0 works flawlessly on jenkins.

**Comment by galexv** [comment]
Blacklisted gcc-4.2, hope it fixes the problem. Closing for now.

**Comment by aeantipov** [comment]
It might be a different version of standard library

**Comment by galexv** [comment]
Possible, but it looks more like some namespace look-up problems.
