### ISSUE TITLE
A number of tests fail with ICC 13.0.2 on MacOS X in Release build configuration

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#131]
The failures are "deallocating memory which was not allocated", and in Debug configuration (`-g`) they disappear (the "heisenbug" behavior). Trying the luck with `-O2 -g` now.

**Comment by egull** [comment]
FYI on ICC 15 I just checked in on mac and it seems to pass all tests. ICC problem?

**Comment by galexv** [comment]
Possibly --- because g++ also has no problems. The question is whether to support icc 13.0...

**Comment by egull** [comment]
I would say yes. This points to an underlying problem that may be present in all builds, but only show up in a crash here.

**Comment by galexv** [comment]
Cf #134

**Comment by galexv** [comment]
Looks like fixed by cf14a3944.
