### ISSUE TITLE
Find MPI properly during CMake phase

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#132]
Currently, if compilers are set to `mpicc` and `mpicxx`, the generated imported `alps::*` targets do not have any information about the location of MPI libraries and headers. Therefore, to use them, one has to find MPI and link it to the project explicitly, or just use `mpicxx` / `mpicc` as a compiler. I think this can lead to problems, such as user linking with an incompatible version of MPI.

On the other hand, it is convenient to say to CMake "just use whatever MPI this `mpicxx` from". According to documentation, `find_package(MPI)` supports extracting the information from MPI compilers.

**Comment by egull** [comment]
So this is a tricky one. Not for our standard platforms, but for platforms like BlueGene or Cray where these things are hidden in a wrapper. So 'just use whatever CC I give you and test what's available' is more fool proof. I don't know if cmake find routines work properly on those more exotic platforms.

**Comment by galexv** [comment]
On those platforms we can suppress automatic search for MPI and revert to the existing behavior (and advise users to compile their project with `mpicxx`). For example, if MPI is not found but requested, test if  the current compiler supports MPI.

**Comment by egull** [comment]
I think this works now.
