### ISSUE TITLE
Get rid of ALPS_DECL in class and function declarations

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#135]
Do we really need it? If i understand correctly, it is a relict from ALPS support for Windows. It confuses syntax highlighters and may confuse users. There is no need to go through the code and remove it, but do we have to preserve it in a newly-written or modified code?

**Comment by egull** [comment]
Not sure. It was also used to print stack traces in exceptions, if I remember it correctly.

**Comment by galexv** [comment]
`ALPS_DECL` is defined in [`utilities/include/config.hpp.in`](https://github.com/ALPSCore/ALPSCore/blob/7a16e6ecefbc3d5808b1110bbb2012a65effa145/utilities/include/config.hpp.in#L181) specifically to handle Microsoft Visual C++, according to the comment. It is non-empty only if `BOOST_HAS_DECLSPEC` is defined, and Boost defines it, apparently, only for Windows environment (and not Cygwin): see [here](https://github.com/boostorg/config/blob/d44dbf69a4115cc1ce10b180c2a2b8ce66b3ae29/include/boost/config/compiler/gcc.hpp#L106) and [here](https://github.com/boostorg/config/blob/871df563bbd2dff8a1dfb43c5307df61cd446eab/include/boost/config/platform/win32.hpp#L24). However, quoting GCC documentation:

>For Microsoft Windows targets there are alternative methods for including the symbol in the DLL's export table such as using a .def file with an EXPORTS section or, with GNU ld, using the --export-all linker flag. 

We may still retain it in case we one day support Windows, or some other C++ extension that will require additional function/class attributes, but i would think it is unlikely. So i would suggest to stop using it --- anyway we have no way of testing it.

**Comment by egull** [comment]
no, I don't like dead code. I vote for removing it then...
