### ISSUE TITLE
Cannot add vector constant to a vector Result

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#138]
It is not possible to add a vector constant to a Result extracted from a vector-valued accumulator (while it is possible to add scalar constant --- cf. issue #137). For example, the following code:

    using namespace alps::accumulators;
    accumulator_set m;
    typedef std::vector<double> data_type;
    m << NoBinningAccumulator<data_type>("acc"); // vector Accumulator 
    m["acc"] << data_type(3, 0.0);
    result_set res(m);
    res["acc"]+data_type(3, 0.0); // adding a constant vector to the result

does not compile. 
**Question**: does anyone need this to work?

**Comment by egull** [comment]
I don't need this. I think it's one of those 'nice to have' features. It makes sense to build it in if we have other arithmetic operations, but it's not a priority.

**Comment by aeantipov** [comment]
Never used it.

**Comment by galexv** [comment]
Then i am closing it as "won't fix". If we decide we need this feature, we can reopen it.
