### ISSUE TITLE
hybridization expansion bug

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#139]
Lewin (Werner group) seems to have found a case where the old hybridization expansion solver from ALPS seems to have a problem. Rather than fix it in old ALPS, we could make it dependent on ALPSCore and fix it in the new ALPS, and have it as an example application dependent on ALPSCore?

**Comment by aeantipov** [comment]
There we go 
https://github.com/ALPSCore/hybridization
I moved over the hybridization part with it's history, added some missing files and made some compatibility changes. Right now it compiles as a library, but likely does not work and the front-end executable needs to be updated. Some other issues are also added under https://github.com/ALPSCore/hybridization/issues

**Comment by egull** [comment]
ok... we'll deal with this in the hybridization repo. Closing here.
