### ISSUE TITLE
inconsistency between params argc/argv and boost mpi argc/argv

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#140]
Our argc/argv in parameters are of type:
unsigned int argc, const char* argv[]
whereas boost mpi wants to create environments 
int argc, char* argv[]
...note the missing const in boost MPI.

how do I pass command line args into boost::mpi and our parameters? Looks like const char* argv[] is a good choice, whereas boost MPI's argv[] is not (why would you modify your command line arguments?)

Any opinions?

**Comment by aeantipov** [comment]
I do 
<pre>
int main(int argc, char* argv[])
{
    alps::params p(argc, (const char**)argv);
    ...
}
</pre>
That seems to work with params and mpi (credit goes to @galexv )

**Comment by egull** [comment]
ok... works for me.
