### ISSUE TITLE
When no measurements are done for an observable, save_results fails

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#141]
If a code has observables that for some reason are not measured (e.g. because the measurement is switched off by the user, etc) the program fails with an exception No Measurement in alps::save_results.

Previously the observables would just be ignored and not written.

@galexv, @aeantipov : I'll send you a demo program that illustrates the problem.

**Comment by aeantipov** [comment]
This has been a problem for me for a while as well as I experienced it in #82 . I did the following workaround:
<pre>
alps::accumulators::result_set results;
            for (std::string x : mc.result_names()) { 
                if (results_sim[x].count()) {
                    results[x] = results_sim[x];
                    };
                };
         ...
            ar[top + "/results"] << results;
</pre>

**Comment by aeantipov** [comment]
Here of course you try to save the simulation, but I guess the root of the problem is the same.

**Comment by egull** [comment]
Ah, now I see what you meant by #82. We'll need to make this work, because most alps codes have unused observables somewhere and just call save_results in the end.

**Comment by aeantipov** [comment]
We can put a similar fix to alps::save_results or to fix the save method for empty accumulators. The latter is probably better, but harder to do.

**Comment by galexv** [comment]
Interestingly, only `FullBinningAccumulator<T>` fails, and only for results. Other results and accumulators are saved fine (but `T=vector<U>` types fail on loading,  see issue #155).
