### ISSUE TITLE
setting default value for vector/list parameter

### ISSUE THREAD

**Issue by guycohen** [ALPSCore/ALPSCore#142]
terminate called after throwing an instance of 'std::logic_error'
  what():  Should not happen: setting default value for vector/list parameter
Aborted (core dumped)

Hi Alex,
Why should this not happen?

**Comment by aeantipov** [comment]
Guy, it's in dev now - see #110

**Comment by galexv** [comment]
In brief, it's a bug. :) Rather in the error message than in the control
flow. Will be fixed with #110.

**Comment by guycohen** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    OK, thanks!
      
      On 06/09/2015 10:51 AM, Alexander Gaenko wrote:
    
    In brief, it's a bug. :) Rather in the error message
      than in the control
      flow. Will be fixed with #110.
      On Jun 9, 2015 10:44 AM, "Andrey E. Antipov"
      <notifications@github.com>
      wrote:
      
      > Guy, it's in dev now - see #110
      > <https://github.com/ALPSCore/ALPSCore/issues/110>
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/ALPSCore/ALPSCore/issues/142#issuecomment-110387532>.
      >
      —
        Reply to this email directly or view
          it on GitHub.
