### ISSUE TITLE
parameter help formatting

### ISSUE THREAD

**Issue by guycohen** [ALPSCore/ALPSCore#143]
Here's an example help message I currently get:

guy@guy-thinkpad:cxx$ ./qmcrunner  --help

  --dot.energies arg                    On-site state energies
  --dot.h arg (=0)                      On-site time-dependent magnetic field 
                                        magnitude.
  --dot.omega arg (=0)                  On-site time-dependent magnetic field 
                                        freuqency.
  --general.dt arg (=0.10000000000000001)
                                        Discretization for propgation time
  --general.dt_bare arg (=0.001)        Discretization for bare propagator 
                                        (typically smaller than dt)
  --general.t_inchworm arg (=0.20000000000000001)
                                        Time at which to begin inchworm 
                                        resummation
  --general.tmax arg (=1)               Maximum propagation time
  --help                                Provides help message
  --lead.Gamma arg (=1)                 Maximum coupling density
  --lead.beta arg (=1)                  Inverse temperature
  --lead.cutoff_factor arg (=100)       Band cutoff factor
  --lead.domega arg (=0.01)             Frequency discretization
  --lead.mu arg (=0)                    Chemical potential
  --lead.nu arg (=10)                   Band inverse cutoff width
  --lead.omega_c arg (=10)              Band cutoff frequency

It would be nice to have:
(a) e.g. 0.10000000000000001 formatted as 0.1.
(b) --help at the end, separated from parameters.
(c) a syntax string at the beginning.
(c) parameters listed in the order of define<> calls rather than alphabetical order.
(d) does the "arg" appearing after every parameter serve a purpose?

**Comment by galexv** [comment]
I will look at it. There must be a way to convince boost::cmdline to format
the help message in a certain way.

**Comment by ryanlevy** [comment]
It'd also be nice to have something like this implemented: [http://www.boost.org/doc/libs/1_50_0/doc/html/program_options/howto.html#id2522664](http://www.boost.org/doc/libs/1_50_0/doc/html/program_options/howto.html#id2522664)
The output from that example looks like:
```
Allowed options:

General options:
  --help                 produce a help message
  --help-module arg      produce a help for a given module
  --version              output the version number

GUI options:
  --display arg          display to use

```

**Comment by egull** [comment]
Will be dealt with in #195

**Comment by egull** [comment]
Alex, I think we're done with this... close?

**Comment by galexv** [comment]
Help message does look better now, so probably ok to close.
