### ISSUE TITLE
Notify user of unused parameters 

### ISSUE THREAD

**Issue by ryanlevy** [ALPSCore/ALPSCore#151]
Because parameters that aren't defined are ignored, a useful feature would be to output unused parameters that were supplied. Something similar to the warning cmake gives maybe?

```
...
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    TEST
    TEST2
```

**Comment by egull** [comment]
Will be dealt with in #195

**Comment by galexv** [comment]
Often a program (e.g., a solver) is called as a subprocess from another code (e.g., DMFT) and share the parameter file with the calling code. Therefore, such a warning would be pretty much useless: it will always report a lot of unused parameters, both for the child and for the parent programs.

Now, if the search of unused parameters will be restricted to a certain section (e.g., [dmft]), it might be more useful --- but this needs a discussion. I am postponing implementing this feature to another release.

**Comment by galexv** [comment]
Addressed in the new parameter library, see issue #377 and commit 
f74dd84.
