### ISSUE TITLE
print undefined parameters 

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#156]
Here's a code snippet: 
```
hybridization::define_parameters(parameters);
std::cout << parameters;
``` 
and inside of define_parameters
```
.define<double>("MU", "chemical potential") \\ note the absence of default parameter
```

When this parameter is not passed the code crashes with the error:
` libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Attempt to print uninitialized option value `. 

Do we use this as a default behavior or it's better to print all parameters that are defined?

**Comment by galexv** [comment]
Commit 2788edee: do not print undefined parameters. 
Does it work?

**Comment by aeantipov** [comment]
It works, thanks!
