### ISSUE TITLE
accumulators: direct access to time series

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#158]
It is often helpful, to access the time series of data for custom operations (for example calculating histograms), not provided by accumulators. 
Having something like `data["name"].begin(); data["name"].end()` or `data["name"].data()` for a (const) pointer to the beginning of time series would allow for more customization.

**Comment by egull** [comment]
We'll go over this some more because it seems the lattice FK code needs this. For now won't fix, potentially in a later state we'll add a TimeSeriesObservable that stores everything if really needed.
