### ISSUE TITLE
Linking failure on Mac with clang and Intel for MacPorts boost 1.59.0_1

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#161]
(Detected after uploading the fix for #79).
Actually not our problem, but i document it here for future reference.

Building on Mac fails at the linking stage with the diagnostics similar to:
```
Undefined symbols for architecture x86_64:
  "boost::archive::basic_text_iprimitive<std::istream>::~basic_text_iprimitive()", referenced from:
      alps::params_ns::params::load(alps::hdf5::archive&) in params.cpp.o
      boost::archive::text_iarchive::~text_iarchive() in params.cpp.o
      boost::archive::text_iarchive::~text_iarchive() in params.cpp.o
  "boost::archive::basic_text_oprimitive<std::ostream>::~basic_text_oprimitive()", referenced from:
      alps::params_ns::params::save(alps::hdf5::archive&) const in params.cpp.o
      boost::archive::text_oarchive::~text_oarchive() in params.cpp.o
      boost::archive::text_oarchive::~text_oarchive() in params.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [params/libalps-params.dylib] Error 1
```

This is caused by a bug in Boost, see:

* MacPorts discussion: https://trac.macports.org/ticket/48717
* Boost discussion: https://svn.boost.org/trac/boost/ticket/11671

**Comment by galexv** [comment]
This is reportedly fixed upstream, but not yet in Macports.

**Comment by egull** [comment]
Yep, can't do much until boost has its new release on December 9 (which will propagate to macports a little later). I propose to wait until then

**Comment by egull** [comment]
fixed upstream, fixed in macports, works for us.
