### ISSUE TITLE
CMake picks old user-installed GTest

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#163]
Reported by James (@jpfleblanc): 
> I am able to configure ALPSCore [...]  It says it cannot find doxygen but throws no error.
> [...]
> However, when it doesn't find doxygen, it seems to not compile gtest as it's first step in the make
> process.  So all subsequent linking cannot find gtest.

**Comment by aeantipov** [comment]
I think it is my yesterday's bug, when I was changing gtest path. Shouldn't be anyhow related to doxygeb

**Comment by galexv** [comment]
It was reported a week ago. :)

**Comment by aeantipov** [comment]
haha, ok. I can try to reproduce it )

**Comment by aeantipov** [comment]
In my case, everything works:
``-- Building documentation for sources in  /Users/antipov/code/alpscore/utilities/include /Users/antipov/code/alpscore/utilities/src /Users/antipov/code/alpscore/hdf5/include /Users/antipov/code/alpscore/hdf5/src /Users/antipov/code/alpscore/accumulators/include /Users/antipov/code/alpscore/accumulators/src /Users/antipov/code/alpscore/params/include /Users/antipov/code/alpscore/params/src /Users/antipov/code/alpscore/mc/include /Users/antipov/code/alpscore/mc/src
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done``
and then everything goes on

**Comment by galexv** [comment]
Got clarification/update from James, changed the issue title.
The problem seems to be that if GTest is user-installed, CMake will pick it --- and later fail.

**Comment by aeantipov** [comment]
That is actually, what I updated. master branch only uses gtest inside of alpscore

**Comment by galexv** [comment]
James confirmed (a few days ago) that it works. Time to close this.
