### ISSUE TITLE
params int to bool conversion fails

### ISSUE THREAD

**Issue by ryanlevy** [ALPSCore/ALPSCore#168]
Similar to #166, `alps::params` does not implicitly cast an int (1,0) input as bool.

```
alps::params p(argc, argv);
p.define<bool>("yes",0,"is this true?"); //works
p["yes"] = 1; //error!
```
On the other hand, command line input (`--yes 1`) works.

**Comment by galexv** [comment]
My comment on #166 is applicable here: the "narrowing" conversion (e.g., `int` to `bool`) is prohibited by design (how would one interpret `p["yes"]=43` ?). In this case, one should use `p["yes"]=true;`. 

I would think that any potentially information-losing conversion should be explicit. However, if the implicit information-losing conversions are really useful, i can consider bringing them back...

**Comment by aeantipov** [comment]
Here I would probably disagree. According to C++ standard ( http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf ) integer types can be casted to each other. 
Specifically, 
```
If the destination type is unsigned, the resulting value is the least unsigned integer 
congruent to the source integer (modulo 2^n where n is the number of bits used 
to represent the unsigned type).
```
So my take would be that we should allow to convert between bool and int in both ways.

**Comment by galexv** [comment]
This is true, but might be considered a C legacy. :) For example, similar conversion does not work for template parameters (http://stackoverflow.com/a/24346350). 

Allowing implicit narrowing conversions (e.g., `double` to `int`) can result in the following problem:
```c++
alps::params p;
p["number"]=10; // acquired type `int`
p["number"]=12.5; // oops! silently truncated.
assert(12.5 == p["number"]); // fails!
```

We can allow conversions specifically for `int` -> `bool`, of course, and even check at run time whether the value is 0 or 1, but i would simply declare that we prohibit narrowing conversions. How often one needs to convert int to bool implicitly in parameters?
