### ISSUE TITLE
Set up proper statistical tests for accumulators

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#172]
What are the "correct" values for the error bars and autocorrelation lengths for accumulators? How to test them properly? 
Ensure that the "correct" values are printed out too (Cf issue #83, issue #129).

**Comment by egull** [comment]
Markus, I'm assigning this to you. It's low priority but would be a good use of hypothesis testing.

**Comment by mwallerb** [comment]
Fine.

Proposed Roadmap: 
* Set up a linear autoregressive process (AR(1))
* Bin it
* In this case the integrated and exponential autocorrelation time coincide with the characteristic relaxation of the process -- verify it stochastically.

**Comment by galexv** [comment]
There is a code in [`accumulators/test/accumulator_generator.hpp`](https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/test/accumulator_generator.hpp)
 (admittedly, wanting some refactoring) that [generates autocorrelated data](https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/test/accumulator_generator.hpp#L124): in my understanding, it implements [AR(L)](https://en.wikipedia.org/wiki/Autoregressive_model#Definition) with equal weights (φᵢ=`1/(L+1)` ) or something reasonably close to it. May it be used as a start?
