### ISSUE TITLE
C++-11 features for friend class

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#177]
Both clang and icpc complain about the following line:

/Users/egull/ALPSCore/ALPSCore/install/include/alps/accumulators/feature/max_num_binning.hpp(381): warning #3670: extended friend syntax is a C++11 feature
                      friend vector_result_type;

**Comment by galexv** [comment]
This will go away with the custom_type patches (issue #157).

**Comment by galexv** [comment]
Fixed.
