### ISSUE TITLE
not_implemented complains because no return value

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#180]
icc warns because there is no return value here:

In file included from /Users/egull/ALPSCore/ALPSCore/accumulators/test/custom_type.cpp:13:
/Users/egull/ALPSCore/ALPSCore/accumulators/test/custom_type.hpp:344:107: warning: control reaches end of non-void function [-Wreturn-type]
        template <typename T> inline my_custom_type<T> cosh(my_custom_type<T>) { not_implemented("cosh"); }
                                                                                                          ^

...and similar for other geometric functions.

**Comment by galexv** [comment]
Should be fixed now.
