### ISSUE TITLE
accumulator tests: switch to ASSERT_NEAR

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#181]
There is a bunch of tests that fails (UNIX): 
The following tests FAILED:
      7 - mean (Failed)
      8 - mean_wrapped (Failed)
     15 - save_load (Failed)

The pattern is common: ASSERT_EQ fails, while visually having the same two numbers as an input. 
For example in mean: 
`
/global/homes/a/aantipov/code/alpscore/accumulators/test/mean.cpp:44: Failure
Value of: T(i + 1) / 2
  Actual: 385
Expected: mean_vec_2[j]
Which is: 385
`

Given that accumulators are floats it might make sense to use ASSERT_NEAR(num1, num2, prec) with `prec  = std::numeric_limits<double>::epsilon()`. Should I just do that?

**Comment by egull** [comment]
Yes, but double epsilon may still cause problems. Use some other small number instead (10^-10 or so)

**Comment by aeantipov** [comment]
Ok, fixed.

**Comment by galexv** [comment]
It seems it still fails, and for the same reason, with ICC v.15.
10^-10 is too small -- the reported differences are more than `3.E-05` in some cases. Needs some additional look, IMHO.

**Comment by galexv** [comment]
And interestingly, `mean` test reports the errors only for `float` vectors (not for scalars, not for `double` or `long double`). The error appears only in the optimized build (with `-O2`). Something fishy (conversion float->double->float?) happens in the vector code, possibly.

**Comment by galexv** [comment]
Needs a second look later, works for now.

**Comment by egull** [comment]
This bug seems awfully irrelevant now that accumulators have been rewritten completely. @mwallerb , is this an actual problem with your ALEA or can we close this?

**Comment by mwallerb** [comment]
@egull . Two parts:

1. It shouldn't be a problem in ALEA, we use my new `ALPS_EXPECT_NEAR` there 
(https://github.com/ALPSCore/ALPSCore/blob/master/utilities/include/alps/testing/near.hpp), so in this case we can close it.

2. The bug now seems to revolve around tests failing, which is bad even for a legacy library, since we still ship it.  Is this still the case? @galexv

**Comment by egull** [comment]
No, tests do not fail. And as you used EXPECT_NEAR, I will close this.
