### ISSUE TITLE
Cori problems with static linking and boost mpi

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#185]
How to compile on Cori with the wrapper compiler?

**Comment by aeantipov** [comment]
This is my script
```
module load boost
module unload cray-hdf5
module unload hdf5
module load myhdf5

rm -rfv CMakeCache.txt CMakeFiles

cmake \
-DCMAKE_INSTALL_PREFIX=${HOME}/modules_cori/alpscore \
-DCMAKE_BUILD_TYPE=Release \
-DBuildStatic=ON \
-DBuildShared=OFF \
-DTesting=ON \
-DHDF5_USE_STATIC_LIBRARIES=ON \
-DBoost_USE_STATIC_LIBS=ON \
-DCMAKE_CXX_FLAGS_RELEASE="-std=c++11 -O3 -DNDEBUG -static -static-libgcc" \
..
```

HDF5 was compiled separately using wrapper

**Comment by aeantipov** [comment]
Here's some more information.

I did `module load zlib` and compiled hdf5-1.8.12 with `configure --enable-static=yes --enable-shared=no --with-zlib=${ZLIB_DIR}/lib`

Then, **myhdf5** module is just
```
-------------------------------------------------------------------
/global/homes/a/aantipov/modulefiles_cori/myhdf5:

setenv		 HDF5_ROOT /global/homes/a/aantipov/modules_cori/hdf5
-------------------------------------------------------------------
```

The module/compiler setup is
```
   module unload intel
   module unload gcc
   module load gcc/4.8.1
   module load intel/15.0.1.133
   module unload numpy
```
Here the versions are only to support c++11, so you most likely don't need them.

**Comment by egull** [comment]
OK. To make it work I also had to compile my own hdf5 (and hack its configure script to exclude libdl at link time), and then change the ALPS cmake script to not search for .so libraries. After changing intel from 16 to 15 (it seems their boost was compiled with intel 15) it even found the right libraries and started to work.

**Comment by aeantipov** [comment]
Here's what I got from the support, when I was doing it 
```
Hi Andrey, The references are from zlib I believe. Can you load the cray-hdf5 module and remove /opt/cray/hdf5/1.8.14/INTEL/14.0/lib/libhdf5.a from your link line (to let the module correctly set up the link line). After that, I suspect it will work. I think having that explicitly there messes with the link order.
```

I remember that helped with static linking with existing hdf5
