### ISSUE TITLE
Abstract dict class in alpscore (from params)

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#187]
A useful application of alps::params is for storing data of different types in one container (i.e. strings, arrays, number). It can be then later retrieved via `.as<dtype>` call. Yet for that no command line inferface, etc are needed. The question is, should such a functionality be taken out into a separate base class, that params would then use?

**Comment by egull** [comment]
Looks to me like Params is not the right place to do this. If you need something like this, could do it in a memory hdf5 file instead? That requires no change...

**Comment by aeantipov** [comment]
Here's a use case, I run Monte Carlo and have a bunch of complex numbers, an array of floats and some ints/doubles as an output. All of that I wanna return to some function, that then parses the data. What would be a good way to do that?

**Comment by galexv** [comment]
In fact, i have been thinking for some time of splitting "dictionary" and "cmdline arguments" features of `alps::params`; it would make the code both conceptually simpler and easier to maintain.

I think `alps::params` does include most of the needed functionality: associative array with dynamic typing. Although alps::hdf5 supports it, in a way, it is less convenient to use:
```C++
{
    alps::hdf5::archive ar("tmpfile","w"); // suppose we make it in-memory file w/o explicit name.
    ar["dbl"]=5.5; // store a double
}
{
    alps::hdf5::archive ar("tmpfile","r");
    
    double xx=ar["dbl"]; // (1) OOPS! compile-time error, no such conversion
    double x;  ar["dbl"] >> x; // (2) works, but inconvenient
    int ii;
    ar["dbl"] >> ii; // (3) OOPS! silent precision loss
    std::cout << "ii=" << ii << std::endl; // prints 5
}
```
All these issues are surely fixable, but alps::params is closer to the target. :)

**Comment by galexv** [comment]
This will require some redesign but does not change the `params` class functionality, so i am pushing this to a later release for now.

**Comment by galexv** [comment]
A separate dictionary class is implemented in the new parameters library (although it's not abstract; it might become one in the future).
