### ISSUE TITLE
mc::stop_callback non-mpi callback for mpi runs required

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#193]
I'm having a following issue - I run an alpscore::mcbase inherited code for a fixed time. 
I measure runtimes, and often I see smth like this:
``` 
runtime =+2s ( time_to_run = +8.000000 )
```

The runtime is measured by std::chrono, while time_to_run is used in alps::stop_callback. The code looks like this
 ```
start = steady_clock::now();
mc.run(alps::stop_callback(time_to_run))
end = steady_clock::now();
std::cout << "runtime =" << duration_cast<seconds>(end - start).count() 
          << " time_to_run = " << time_to_run << std::endl;
```

The issue probably comes with the fact, that the non-mpi code mcbase is called, while ALPSCore has ALPS_HAVE_MPI enabled, prompting callback to check over the network, i.e. from mc/src/stop_callback.cpp one sees
```
    bool stop_callback::operator()() {
#ifdef ALPS_HAVE_MPI
        if (comm) {
            bool to_stop;
            if (comm->rank() == 0)
                to_stop = !signals.empty() || (limit.count() > 0 && boost::chrono::high_resolution_clock::now() > start + limit);
            broadcast(*comm, to_stop, 0);
            return to_stop;
        } else
#endif
            return !signals.empty() || (limit.count() > 0 && boost::chrono::high_resolution_clock::now() > start + limit);
    }
}
```

The trick is that in my case many independent single-cpu Monte-Carlo runs are done, while the results are collected via network. So a non-mpi version of callback is required. And the solution is of course to extract a non-mpi stop_callback and just use it. 

Still it might be a good idea to have smth like ```simple_stop_callback``` class which does not use mpi communication. What do you think?

**Comment by galexv** [comment]
Looking at the code...
It seems one can pass `boost::none` as communicator when creating `stop_callback` object, then it will not try to use MPI even if it available: the communicator is `boost::optional`.
Does it make sense / is it relevant?

**Comment by aeantipov** [comment]
Ah, then it's even more strange, because I don't pass a communicator

**Comment by aeantipov** [comment]
Ah, wait, I take my words back - in my case the cause of early exit might be the signal that the queueing system sends.

**Comment by aeantipov** [comment]
But since the issue is raised, Alex, do you think one should make 
```
            boost::chrono::duration<std::size_t> limit;
            boost::chrono::high_resolution_clock::time_point start;
```
const?

**Comment by galexv** [comment]
Well, we can --- the only side-effect would be the loss of default assignment operator, which we probably do not need anyways. 
I've just tried, it compiles and passes tests.

**Comment by galexv** [comment]
Addressed by commits e29d0c06e2 and 55729c86d8.
Shall i close the issue?

**Comment by aeantipov** [comment]
I'd also propose to make signals optional - after all for debugging purposes sometimes it's advantageous to ignore the signals

**Comment by aeantipov** [comment]
Added a simple_time_callback in 13ba083f8d0a382e2cd16f92af69816021a433cc
