### ISSUE TITLE
Accumulators - nan in division

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#194]
I have a following code: 
```
std::complex<double> sign = results["sign_real"].mean<double>() + I*results["sign_imag"].mean<double>();
std::complex<double> sign_norm = results["sign_real_nca_only"].mean<double>() + I*results["sign_imag_nca_only"].mean<double>();

// ref_value is a non-zero std::complex<double> input
// Here comes the code to get output (see below)
std::cout << "sign = " << sign
<< " sign_norm = " << sign_norm
<< " ref_value = " << ref_prop_val
<< " -> output = " << output << std::endl;
```
which gives
```
sign = (-0.0183034,0.00348538) 
sign_nca = (+0.000107,-0.000259) ref_value = (-0.001994,-0.000819) -> 
output = (-nan,-nan)
```
Notice the non-zero sign, sign_nca, ref_value values. 

This code works and gives a non-nan value
```
std::complex<double> output = sign / sign_norm * ref_value;
```

This sometimes fails
```
auto acc_denom = results["sign_imag_nca_only"]*results["sign_imag_nca_only"] + results["sign_real_nca_only"]*results["sign_real_nca_only"];
auto prop_real_acc1 = (results["sign_real"] * results["sign_real_nca_only"] + results["sign_imag"] * results["sign_imag_nca_only"]) / acc_denom;
auto prop_imag_acc1 = (results["sign_imag"] * results["sign_real_nca_only"] - results["sign_real"] * results["sign_imag_nca_only"]) / acc_denom;
auto prop_real_acc = prop_real_acc1 * ref_value.real() - prop_imag_acc1 * ref_value.imag();
auto prop_imag_acc = prop_real_acc1 * ref_value.imag() + prop_imag_acc1 * ref_value.real();
std::complex<double> output = prop_real_acc.mean<double>() + I * prop_imag_acc.mean<double>()
```
Everything in results are FullBinning accumulators

**Comment by aeantipov** [comment]
Added a failing divide_accumulators2 test in e77da80259565e759ee817e03c2c7c3eb208bf0d

**Comment by egull** [comment]
This result is perfectly consistent with what it should be. If you write your bins into a file and run the attached python script that does the jackknife by hand you find exactly the same result:

import numpy as np

val2=np.loadtxt('bins.dat')
print val2

print "Naive mean: ",1.5/np.mean(val2)

#the function: divide 1.5 by x
def fun(x):
  return 1.5/x

#jackknife: average of all but the i-th bin
def all_but_i(i, val):
  return (np.sum(val)-val[i])/(val.size-1)

def ui(val):
  ui=np.zeros(val.size)
  for i in range(val.size):
    ui[i]=fun(all_but_i(i,val))
  return ui

val2_ui=ui(val2)
val2_ubar=np.mean(val2_ui)
val2_uzero=fun(np.mean(val2))
print "ubar: ",val2_ubar
print "uzero: ",val2_uzero
print "jackknife mean: ",val2_uzero-(val2.size-1)*(val2_ubar-val2_uzero)
print "jackknife error: ",np.sqrt(val2.size-1)*np.sqrt(np.mean(val2_ui*val2_ui)-val2_ubar*val2_ubar)

**Comment by egull** [comment]
OK, talked this through and decided the test divide_accumulators2 is not what's happening here – need more info.

**Comment by egull** [comment]
Looks like all the math is correct and something in the application code is causing the problems.
