### ISSUE TITLE
Discuss and implement Parameter enhancements / Interface changes on user side

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#195]
The following enhancements have been requested and will need to be discussed:

1. Arithmetic and comparison operations with parameters, #190 
2. Complex numbers as parameters #188 
3. Implicit conversion, e.g. int to bool #166 
4. Notification of unused parameters, #151 
5. Parameter help formatting, #143 
6. Improvement of help requested, #124 
7. Vector values with default parameters, #110 
8. Support for vector of strings, #103 
9. Disabling input from command line, #104 

...for the next parameters release, v.0.5.5. I'm closing all of those individual requests so we can discuss them together here.

**Comment by ryanlevy** [comment]
Similar to #143 , I suggest writing the variable type in the message. This avoids situations like
````
     --SELF arg (=0)                    input is a self energy
     --SHIFT arg (=0)                   shift of a model
```` 
where `SELF` is a bool and `SHIFT` is a double. (It does not appear to have an easy boost solution)

**Comment by galexv** [comment]
We discussed. Critical issues are addressed, all nice-to-have features are moved to a dedicated release, all maybe-some-day features are moved to a catch-all release.
