### ISSUE TITLE
CMake attempts to compile `ostream` executable

### ISSUE THREAD

**Issue by jgreitemann** [ALPSCore/ALPSCore#201]
I've encountered a very strange problem. I'm not sure if this is a bug in ALPSCore of if my environment is messed up for some reason.

When I compile the project, everything is fine up to the point where the `ostream` test is compiled. Every target that is compiled afterwards fails because for some reason the compiler actually tries to compile the `ostream` executable as if it was a source file. Consider this [output.txt](https://github.com/ALPSCore/ALPSCore/files/199795/output.txt). If I built the target `ostream` first, the subsequent build of `predicates_and_action` (which would be the next target when building `make all` but really is an arbitrary choice on my part) yields a ton of errors resulting from `g++` trying to parse an ELF binary (`build.tmp/params/test/ostream`) as source code. Had I built `predicates_and_actions` first, no error would've occurred. In fact, I'm able to successfully compile everything by building the `ostream` target last.

This problem occurred on my workstation at university, so I have no control over the environment. It runs Ubuntu 14.04, `cmake 2.8.12.2`, `g++ 4.9.2`, and `Boost 1.54.0`. I'm unable to reproduce the problem on my personal computer which runs Fedora 23 and the current versions of `cmake` and `g++`.

The problem pertains to the current version as of this writing (`8f288c`) as well as earlier versions including the last release `v0.5.3`.

**Comment by galexv** [comment]
My wild guess: somewhere (presumably in `/software/opt/trusty/x86_64/gcc/4.9.2/include/c++/4.9.2/iostream`, line 39) there is `#include <ostream>` or `#include "ostream"` or something similar. And GCC is searching for headers files starting from the current directory, which contains file `ostream`. 

If it is so, renaming the executable to something else (e.g. `param_ostream`) should work around this problem.

I have just pushed a quick fix --- would you mind trying it?

**Comment by jgreitemann** [comment]
That did the trick indeed.
