### ISSUE TITLE
Do not include current directory in header search paths?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#202]
See issue #201. 
The underlying problem is that `-I.` in the compiler invocation means, according to [GCC 4.9.2 documentation](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/cpp/Search-Path.html#Search-Path), that the headers (even the "system" headers in angular brackets!) are first searched in the current directory. As a result, if, e.g., a generated executable accidentally named the same as a standard header, we have an unexpected behavior, as #201 demonstrated. 
It seems to me that there is no actual need of including the current directory in the header search path. If we want to include a file in the current directory, we should just put its name in quotes (`#include "local_header.hpp"`).

**Comment by egull** [comment]
I agree – I see no idea to have -I. change it?

**Comment by egull** [comment]
I checked this – I can't find a -I. in any of my includes. Do you know where it could come from? Was it specified on the command line?

**Comment by jgreitemann** [comment]
`-I.` does not appear in the compiler flags when running `VERBOSE=1 make`.

I did install ALPSCore to `$HOME/.local` on my machine by passing `--prefix` to `cmake` as I don't have root access on my university workstation. I also added `$HOME/.local/include` to my `$CPLUS_INCLUDE_PATH` in `.bashrc`. (This is not necessary for ALPSCore, as `cmake` will take care of it, but I have other headers in there, too.) Unsetting this environment variable actually solves the issue for me, i.e. ALPSCore will compile even in the revision without the `ostream` test renamed. That said, I'm not sure if this is just ill-advised configuration on my part, or a bug in ALPSCore. I still don't see why the file in `build.tmp/params/test/` would be included.

**Comment by egull** [comment]
Alex, do you have more information or should we close as invalid? Any idea which dependency might pull in -I. sometimes?

**Comment by jgreitemann** [comment]
Got it now. In my `.bashrc`, I had something to the effect of

    export CPLUS_INCLUDE_PATH=$HOME/.local/include:$CPLUS_INCLUDE_PATH

However, if the variable is initially empty, I get

    $ echo $CPLUS_INCLUDE_PATH
    /home/j/J.Greitemann/.local/include:

Note the trailing colon. In the [GCC documentation](https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html), it reads:

> In all these variables, an empty element instructs the compiler to search its current working directory. Empty elements can appear at the beginning or end of a path. For instance, if the value of `CPATH` is `:/special/include`, that has the same effect as ‘`-I. -I/special/include`’.

So, the problem was definitely on my part. Sorry for bothering you with this.

**Comment by egull** [comment]
ok, closing as 'invalid'.

**Comment by galexv** [comment]
Still, it's good to be careful with naming executables, to make ALPSCore more robust. :)
