### ISSUE TITLE
Enforce no-assert GF build by default

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#209]
Enforce no-assert compilation and, if possible, high-optimization compilation options when linking with ALPSCore GF, unless specifically requested by a user to not do so.

[Transplanted from ALPSCore/GFTools#9]

**Comment by egull** [comment]
done by introducing a header that gives a warning if NDEBUG and BOOST_DISABLE_ASSERTS are not defined, unless the user wants that.
