### ISSUE TITLE
Arithmetic op between NoBinning and FullBinning

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#210]
As reported by @egull, dividing a NoBinning result by a FullBinning result causes a "bad cast" exception thrown.

**Comment by galexv** [comment]
A workaround for this missing feature  is implemented (but not yet properly tested):
```C++
    namespace aa=alps::accumulators;
    aa::result_set rset;
    // ....
    const aa::result_wrapper& r1=rset["no_binning"];
    aa::result_wrapper r2=aa::cast<aa::FullBinningAccumulator,aa::NoBinningAccumulator>(rset["full_binning"]);
    aa::result_wrapper rsum=r1+r2;
```

**Comment by galexv** [comment]
Once issue #172 is addressed, the test can be added and this issue can be closed.

**Comment by egull** [comment]
Won't test extensively because we have new accumulators.
