### ISSUE TITLE
Expand param ini tutorial

### ISSUE THREAD

**Issue by ryanlevy** [ALPSCore/ALPSCore#217]
ALPSCore (through `Boost::program_options`) has a useful but somewhat hidden parameter feature. Consider:
````c++
par.define<int>("phys.num.implosions","Number of implosions");
````
This allows for naming via the usual `phys.num.implosions=42` but in an ini file we can write
````ini
[phys.num]
implosions=42
````
That way for larger projects we can structure the code 
````ini
[phys.num]
implosions=42
booms=5
[phys.const]
plank=1
````
which will implicitly structure the help message too. I think it would be useful to explicitly add it to the tutorials.

**Comment by galexv** [comment]
Yes, a good point.
This feature is not as "hidden" as it looks --- its presence was one of the reason to choose `boost::program_options` as a back end in the first place :) , and it is tested by https://github.com/ALPSCore/ALPSCore/blob/master/params/test/file_read.cpp#L219 --- but it does need to be documented.

**Comment by galexv** [comment]
Because this requires modifications of the ALPSCore code (tutorials part), and we are under effective "code freeze" due to the submission of the code snapshot to CPC, i am moving this issue to the next release (however easy it is to resolve).
