### ISSUE TITLE
Test failures go undetected on Jenkins

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#218]
After running alpscore_osx_cqmp1_intel build on Jenkins (e.g., https://alpscore.ci.cloudbees.com/job/alpscore_osx_cqmp1_intel/107/console), the log shows multiple test failures, while the build is marked as successful and all tests are marked as passed at https://alpscore.ci.cloudbees.com/job/alpscore_osx_cqmp1_intel/107/testReport/ .

**Comment by galexv** [comment]
For the record, the failed tests themselves are fixed (the issue was the wrong Boost libraries picked up). The bug with test failures going undetected still stands for now.

**Comment by egull** [comment]
This is fixed by moving to Travis for the ALPSCore tests. Cloudbees Jenkins will retire.
