### ISSUE TITLE
static building needs to be explained

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#219]
and perhaps other build options? Sergei was struggling to find the right flag...

**Comment by aeantipov** [comment]
Here's one from me from cori
```
cmake \
-DCMAKE_INSTALL_PREFIX=${HOME}/modules_cori/alpscore \
-DCMAKE_BUILD_TYPE=Release \
-DALPS_BUILD_STATIC=ON \
-DTesting=ON \
-DHDF5_USE_STATIC_LIBRARIES=ON \
-DBoost_USE_STATIC_LIBS=ON \
-DCMAKE_CXX_FLAGS_RELEASE="-std=c++11 -O3 -DNDEBUG -static -static-libgcc" \
..
```

**Comment by egull** [comment]
it's clear how to do it. By 'explained' I mean the installation webpage needs to be updated to reflect how to do it so people who are not 'in the know' can find it..

**Comment by aeantipov** [comment]
yeah, I agree. I was pointing to an extra set of flags, like "-DHDF5_USE_STATIC_LIBRARIES=ON" that also need to be put

**Comment by iskakoff** [comment]
I've just checked this. It a little bit weird that when I've just set "ALPS_BUILD_STATIC=ON" I've got the error cause "ALPS_BUILD_SHARED" is "ON" by default.

According to cmake files "HDF5_USE_STATIC_LIBRARIES" is not necessarily to be set cause there is following condition
`
if (ALPS_BUILD_STATIC)
    set(HDF5_USE_STATIC_LIBRARIES ON)
endif()
 `

**Comment by galexv** [comment]
Hi,

Probably "ALPS_BUILD_SHARED=ON" is remembered in CMake's cache, so when
ALPS_BUILD_STATIC is set to ON, there is a conflict (as they are mutually
exclusive).
One has to either unset ALPS_BUILD_SHARED or set it to OFF. I do not think
there is a way to distinguish between a variable in the cache vs a variable
set in the CMake command line.

With best regards,
   Alexander.

**Comment by galexv** [comment]
Added documentation to wiki: https://github.com/ALPSCore/ALPSCore/wiki/CMake-and-environment-variables-affecting-ALPSCore-build. The [installation page](https://github.com/ALPSCore/ALPSCore/wiki/Installation) is modified accordingly.

**Comment by egull** [comment]
cool, thanks a lot! close?
