### ISSUE TITLE
homepage points to unfinished pages

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#221]
the alpscore.org homepage points to TODOs and unfinished & abandoned items.

Examples:
https://groups.google.com/forum/#!forum/alpscore has zero emails. Propose to replace it with a forward to galexv?

https://github.com/ALPSCore/ALPSCore/wiki/Overview

https://github.com/ALPSCore/ALPSCore/wiki/Tutorials lists further ideas

https://github.com/ALPSCore/ALPSCore/wiki/Physics is a complete stub

...etc...

this needs to be fixed before the paper goes out.

**Comment by shinaoka** [comment]
And, how about adding like to applications such as Maxent and CT-HYB?

**Comment by egull** [comment]
Yes, good idea.

**Comment by galexv** [comment]
We need to add more applications to https://github.com/ALPSCore/ALPSCore/wiki/Applications-that-use-ALPSCore, and possibly briefly discuss the relevant physics.

AFAICS, there are no empty pages any more, so i am removing the "Bug" label.
