### ISSUE TITLE
Custom ScheduleChecker in mpiadapter clashes with specialized constructor

### ISSUE THREAD

**Issue by jgreitemann** [ALPSCore/ALPSCore#222]
`mpiadapter` in principle allows for user-defined schedules by overriding the default `alps::check_schedule` in the template parameter `ScheduleChecker`. One then needs to pass in the custom schedule as an object to the general ctor

    mcmpiadapter(
                  parameters_type const & parameters
                , alps::mpi::communicator const & comm
                , ScheduleChecker const & check)

The other ctor is intended to be disabled in this case:

    mcmpiadapter(
                  parameters_type const & parameters
                , alps::mpi::communicator const & comm
                , typename boost::enable_if<boost::is_same<ScheduleChecker, alps::check_schedule>, bool>::type* dummy = 0)

However, when I tried using a custom schedule, I got the error:

    error: no type named ‘type’ in ‘struct boost::enable_if<boost::is_same<MySchedule, alps::check_schedule>, bool>’

The reason is that `enable_if` relies on SFINAE but SFINAE doesn't kick in here since the substitution occurs already on the level of the class rather than that of the member functions. A quick fix is to defer the substitution to the constructor to allow for SFINAE by adding a template parameter that defaults to the class-level one:

    template <typename U = ScheduleChecker>
    mcmpiadapter(
                  parameters_type const & parameters
                , alps::mpi::communicator const & comm
                , typename boost::enable_if<boost::is_same<U, alps::check_schedule>, bool>::type* dummy = 0)

I'd suggest to fix this upstream as it is clearly a bug. On a related note, it would be desirable not to define the parameters `Tmin` and `Tmax` if the default schedule is not used.

**Comment by galexv** [comment]
Jonas (@jgreitemann), thanks for the bug report. 
This particular solution seems to require C++11. I am now considering alternatives that would work with C++03. Do you, by chance, have anything in mind already?

**Comment by jgreitemann** [comment]
Yes, I noticed that default template parameters are not allowed for functions prior to C++11. However, the default is not really necessary: writing just `template <typename U>` is fine, too. The template parameter can be inferred so existing code should not break.

**Comment by galexv** [comment]
Another option i was thinking about is to ask custom schedulers to always have a constructor from `const alps::params&` (which does not have to actually use the argument). Then the whole `enable_if` can be eliminated.

**Comment by jgreitemann** [comment]
In my opinion the 'correct' way to do it is to pass a scheduler object to the constructor, as it is currently the case. By requiring to construct the scheduler from `alps::params` you needlessly limit the flexibility of the user to construct schedulers with third-party dependencies. E.g. I could imagine a situation where the scheduler would interface with the load-leveller at runtime. The whole point of the additional `enable_if` ctor is to provide a convenience feature which hides the additional complexity of schedulers from the user in the majority of cases where they don't really care about it. Thus, I would advocate to keep things as they are and just fix this particular bug, but it's up to you of course.
