### ISSUE TITLE
Add `CONTRIBUTING` file

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#224]
As GitHub [suggests](https://guides.github.com/activities/contributing-to-open-source/), add `CONTRIBUTING` file to the root directory with guidelines about contributing.

**Comment by egull** [comment]
sounds good to me – why not?
There's a 'problem'/bug/feature with the current commits: whoever contributes automatically gets into the zenodo author list (and appears in papers if people cite this) – users may not want to do that, or we may not want them to be authors. We'll need to discuss.

**Comment by galexv** [comment]
It is possible to edit the uploaded release metadata on Zenodo, including authors and affiliations. I, however, suspect that at least in one occasion my edits were ignored. (Zenodo bug? If so, we can complain to them).
