### ISSUE TITLE
Do Release build by default?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#225]
Running `cmake` without `-DCMAKE_BUILD_TYPE=...` builds a version with NDEBUG undefined, issuing warnings from the GF module (Cf. issue #209). It would be nice if `Release` build were default.

**Comment by egull** [comment]
agree. I would even qualify not having NDEBUG and BOOST_DISABLE_ASSERTS defined by default a bug, as it slows down anything based on multiarray to unusable speeds.

**Comment by aeantipov** [comment]
I was looking at boost/assert.hpp header few days ago. Basically if BOOST_DISABLE_ASSERTS is not defined, BOOST_ASSERT becomes equivalent to standard assert, so NDEBUG disables it.

**Comment by galexv** [comment]
I looked at `boost/multi_array/*.hpp`. There are sections that are included if `BOOST_DISABLE_ASSERTS` is not defined; although it seems that whatever code they generate would be optimized out, the documentation to `boost::multi_array` specifies its behavior with respect to defined status of `BOOST_DISABLE_ASSERTS` and not `NDEBUG`, so it is theoretically possible that multi-array behavior is affected by `BOOST_DISABLE_ASSERTS` alone. For example, they might, in the future, define their own `BOOST_ENABLE_ASSERT_HANDLER`. That's why, IMHO, it is safer to define both `BOOST_DISABLE_ASSERTS` and `NDEBUG`.
