### ISSUE TITLE
Suggestion: provide convenience CMake modules for, e.g., GTest

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#229]
The question raised by Sergey  (@iskakoff): it is inconvenient that every software tries to download GTest and use its own `add_gtest()` CMake functions, mostly copy-and-pasted from ALPSCore anyway. 

ALPSCore can provide "CMake library" functions to, e.g., download GTest, and expose its internal `add_gtest()` so that everyone can use it.

**Comment by egull** [comment]
wontfix.
