### ISSUE TITLE
alps-params testing compilation bug

### ISSUE THREAD

**Issue by jpfleblanc** [ALPSCore/ALPSCore#232]
System boost is found, no cmake errors.

alps-params compiles and links to boost
alps-params testing fails to find boost.

workaround: disable add_testing() in ALPSCore/params/CMakeLists.txt

**Comment by jpfleblanc** [comment]
Similarly for

ALPSCore/mc/CMakeLists.txt

Not reproduced on Stampede, or local system.  Likely system configuration issue.

**Comment by terletska** [comment]
James, can i have more details? Maybe a cmake and compilation transcripts?

**Comment by galexv** [comment]
James, sorry -- the previous comment is mine, not Hanna's. :)

**Comment by galexv** [comment]
James, can i have more details? Maybe a cmake and compilation transcripts?

**Comment by jpfleblanc** [comment]
hmmm, unfortunately I did not stash the broken output.   Removing testing worked for compiling ALPSCore, but I could not link CTaux to the slightly broken ALPSCore, it could not find any of the GF definitions.

I'm not 100% sure, but it could be due to outdated instructions on the ALPScore site:

The instructions here: 
https://github.com/ALPSCore/ALPSCore/wiki/Installation

did not work, while instructions here:
https://github.com/CQMP/DMFT/wiki/Installation-instruction

did work.

The key point seems to be the -DALPS_GF_DEBUG .  So I think that was the root of my issue.  So the simple fix is to update the wiki I suppose. I don't really know what these flags are, or if they are always necessary.

As a second point, the -DBOOST_ROOT=/path/to/boost  did not work at all.  It still found the system boost, despite providing the other flags you describe on your ALPSCore wiki.

Let me know if any of this is unclear.

**Comment by galexv** [comment]
More information is probably needed --- see issue #242.
