### ISSUE TITLE
ALPSCore "Physics" page is essentially empty.

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#237]
We can fill it from ALPSCore paper.
Link: https://github.com/ALPSCore/ALPSCore/wiki/Physics
Cf. issue #221.

**Comment by galexv** [comment]
There is not much "physics" in ALPSCore per se --- i would suggest replacing this page with the links to applications (which do contain physics). Emanuel (@egull), would you agree?

**Comment by egull** [comment]
yes. Go for it!

**Comment by galexv** [comment]
Made a page with an (incomplete) list of applications.
