### ISSUE TITLE
Issue with linking with Fortran MPI libraries on Cray machines

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#241]
Reported by Sergey (@iskakoff): There is a difficulty compiling a project that uses both ALPSCore and a Fortran library requiring MPI on Cray machines (namely, on Edison). 

The essence of the problem seems to be that FindMPI finds dynamic rather than static Fortran MPI libraries, and linking fails. ALPSCore does not help, because it itself is compiled using MPI-aware wrapper and does not provide any transitive dependencies on its own (and anyway it would not depend on Fortran MPI libraries).

Question: how to build such a project?

Suggested workaround currently is to find required static Fortran MPI libraries manually and put them into the list of libraries to link with explicitly. 

For me it looks more like FindMPI problem, but an ALPSCore user on Cray would likely bump into it, so if we can suggest and document a workaround, it would be good.

Cf: issue #213, issue #206, issue #160.

**Comment by galexv** [comment]
Sergey (@iskakoff), could you provide some minimal example for testing? (What library, and a minimal code).

**Comment by egull** [comment]
I'd say this is a problem with FindMPI, not with us. We should tell a user to use the wrapper compiler and use static linking. Manually specifying the libraries is a bad idea, and FindMPI simply fails. I will update the documentation accordingly.

**Comment by egull** [comment]
updated. Cray users are now explicitly instructed to use static builds.
