### ISSUE TITLE
bool and complex<double> in ALPSCore/utilities/include/alps/utilities/mpi.hpp

### ISSUE THREAD

**Issue by iskakoff** [ALPSCore/ALPSCore#244]
We have two specific cases for bool and std::complex<double> for bcast and other operations.
Is there some reason to do not use MPI_CXX_DOUBLE_COMPLEX and MPI_CXX_BOOL?

**Comment by galexv** [comment]
Good idea. These types are not mentioned in the [official MPI 2.2 standard](http://www.mpi-forum.org/docs/mpi-2.2/mpi22-report.pdf) or in the prior standards, but are introduced in the [MPI 2.2 errata document](http://www.mpi-forum.org/docs/mpi-2.2/errata-22.pdf). (And they are in [MPI 3.0](http://www.mpi-forum.org/docs/mpi-3.0/mpi30-report.pdf), but we do not support MPI-3 officially.) As we require MPI-2.2-compliant library as a dependency, we can as well make use of `MPI_CXX_DOUBLE_COMPLEX` and `MPI_CXX_BOOL`.

**Comment by galexv** [comment]
Apparently, because  `MPI_CXX_DOUBLE_COMPLEX` and `MPI_CXX_BOOL` are not in MPI-2.2, the packaged version of OpenMPI on Ubuntu 14.04 LTS (openmpi-1.6.5) does not have those types! We will have to check for them --- they may not be there for significant number of users.

**Comment by egull** [comment]
Do we need MPI 2.2 anywhere else or would this be the only place? If we need it somewhere else we should test for it. If we need it nowhere else I'd advocate for not introducing these types, to keep things simple.

**Comment by galexv** [comment]
MPI <2 is really ancient now, we require [MPI-2.1](http://mpi-forum.org/docs/mpi-2.1/mpi21-report.pdf) which is not very new either (2008): we simply do not test ALPSCore with the earlier MPI.

The `MPI_CXX_*` types in question are first mentioned in [MPI-2.2 errata](http://mpi-forum.org/docs/mpi-2.2/errata-22.pdf), added in July 2012. 

The first MPI standard where those types are mentioned upfront is [MPI-3.0](http://mpi-forum.org/docs/mpi-3.0/mpi30-report.pdf), published September 2012. (My current understanding is that "errata" is basically a "diff" between the old and the new standards: that is, errata to MPI-2.2 belongs to MPI-3.0.) 

Therefore, the `MPI_CXX_*` types are actually from MPI-3.0 which we do not require (as of now). 

**Resolution**: The code is there, but requires linking with an implementation of MPI-3.0 standard which is not in the installation prerequisites, therefore the code is inactive. When and if we will need MPI-3+ functionality, this code can be activated.
