### ISSUE TITLE
Tutorials redundancy?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#245]
We have MC tutorials that seem to have partially redundant: `tutorials/mc/02-mcbase` and `tutorials/mc/ising_mc`.

**Comment by galexv** [comment]
They are indeed almost identical (except minor things like class variable declarations that are moved around and different capitalization of parameters), and `ising_mc` seems to be more thoroughly commented. I propose to replace both `01-c++` and `02-mcbase` tutorials with implementations of a simpler/trivial algorithm (like the infamous "finding π") to not obscure the details of programming, and leave 1D-Ising and 2D-Ising as examples of more complex/realistic programs. The trivial MC can be lifted from the group seminar-tutorial / summerschool slides.

**Comment by egull** [comment]
yep, sounds good to me. Keep it simple!
