### ISSUE TITLE
Real-frequency mesh in GF

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#250]
There is an [HDF5 format for the real-frequency mesh](https://github.com/ALPSCore/H5GF/blob/master/H5GF.rst#real-frequency-mesh), but this mesh is not coded in ALPSCore. Sergey (@iskakoff) requested it to be there. :) Should be fairly easy to implement.

**Comment by egull** [comment]
Yes, straightforward to do. But @iskakoff : how would you like to construct your mesh? pass in a vector of points? How about logarithmic / uniform / whatever spacing? Should we grandfather in the real frequency meshes we have in @ryanlevy 's Maxent code?

**Comment by egull** [comment]
... @iskakoff have a look here:
https://github.com/CQMP/Maxent/blob/master/src/maxent_grid.hpp

**Comment by iskakoff** [comment]
@egull Should the MPI broadcast be implemented for real frequency?

**Comment by egull** [comment]
yes, sure!

**Comment by iskakoff** [comment]
#253

**Comment by galexv** [comment]
I have merged pull request #253 (thanks, Sergey!)
However (just to be picky :-) ): 
* it would be nice to have some tests that verify that linear, quadratic, and logarithmic meshes are indeed linear, quadratic and logarithmic. (I did not check the logic of their construction thoroughly; it may be easier to check the logic of the tests);
* Just a suggestion: what about moving the `whatever_grid` classes into a new `grid` namespace, to refer to them as `grid::whatever` ? 
* It would be also nice to have a tutorial-like example on using the meshes and grids.

**Comment by galexv** [comment]
Closing as "done". More tests is a separate issue #257.
