### ISSUE TITLE
Problems with macport for v0.5.5

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#252]
According to MacPorts people, the port did not build:

> # 52462: ALPSCore version update to 0.5.5
> 
> -----------------------+----------------------
>   Reporter:  egull@…   |      Owner:  galexv@…
>       Type:  update    |     Status:  new
>   Priority:  Normal    |  Milestone:
>  Component:  ports     |    Version:
> Resolution:            |   Keywords:  haspatch
>       Port:  ALPSCore  |
> -----------------------+----------------------
> 
> Comment (by mf2k@…):
> 
>  This does not build for me. Apparently due to boost.
> ## 
> 
> Ticket URL: https://trac.macports.org/ticket/52462#comment:3

Looking at the attached log, it must be the same issue as with #247 (namely, [-stdlib=libstdc++](./247#issuecomment-249855213)).

**Comment by egull** [comment]
builds for me – just ran it again. If he has it on macports he cannot enable c++-11 in boost with the standard environment, so I doubt it has something to do with #247. Do we have a 'clean' mac to build it and see it fail?

**Comment by galexv** [comment]
I have a Mac at home, i can try. :)

**Comment by galexv** [comment]
For the sake of completeness, attached [macports compilation log](https://github.com/ALPSCore/ALPSCore/files/506292/alpscore_macports_compilation_log.txt).

This error:
> :info:build Undefined symbols for architecture x86_64:
> :info:build   "boost::program_options::to_internal(std::__cxx11::basic_string<char,std::char_traits<char>, std::allocator<char> > const&)", referenced from:
> [....]

suggests that we again ran into ABI incompatibility between C++11 and C++03. Apparently, ALPSCore is being compiled generating C++11 ABI calls (that's why the `_cxx11` namespace), while Boost was NOT compiled with the same ABI/compiler/compiler options (that's why the symbol is not found). 

The compiler that's been used to compile ALPSCore is (from the logs): `/opt/local/bin/gcc-mp-6`

[This answer from SO](http://stackoverflow.com/a/33395489) may be of relevance to us:
> Defining the following macro before including any standard library headers should fix your problem: #define _GLIBCXX_USE_CXX11_ABI 0

**Comment by galexv** [comment]
The way to fix this issue is found: the recommended MacPorts way is not to use g++ to compile ALPSCore port.

As it turns out to be rather a packaging issue than an issue with MacPorts, i am moving this to a separate issue ALPSCore/packaging#4 (and marking this issue "invalid").

**Comment by galexv** [comment]
Reverting the decision to close: let this issue track all current MacPorts issues: ALPSCore/packaging#4 and ALPSCore/packaging#5.

**Comment by galexv** [comment]
Cross-ref: Issue #255 prevented proper MacPort installation (now fixed).

**Comment by galexv** [comment]
Submitted pull request to macports, let's see if it works for them now.
