### ISSUE TITLE
Compilation picks up the wrong `alps/config.hpp`

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#255]
If ALPSCore is installed system-wide, `#include <alps/config.hpp>` picks up the system-wide header from the currently installed version of ALPSCore, which may not have the same configuration as the version being installed!

E.g., as observed with ALPSCore macport, `port install alpscore` fails: the current build (which is not MPI-enabled) erroneously tries to compile MPI-specific stuff, because the currently installed ALPSCore happens to be MPI-enabled. In more details, the `#include` directive picks up the "system-wide" `/opt/local/include/alps/config.hpp` instead of the "build-local" `/whatever/build/directory/utilities/include/alps/config.hpp`.

**Comment by galexv** [comment]
*Disclaimer*: the following is "work in progress / thinking aloud" and may contain half-baked ideas.

The simplest solution could have been to name the "build-local" and "system-wide" config files differently or simply to not use the "build-wide" config. However, because each of the ALPSCore modules can be built independently (rather than as a part of a single build), they have to rely on the system-wide ALPSCore configuration. Possibly, we can define a macro (something like `-DALPS_NO_STANDALONE`) which would suppress getting the configuration from the system-wide config...

**Comment by aeantipov** [comment]
Alex, this looks not like a bug in alpscore, but rather the fact that macports uses the system-wide environment in the port. It looks like the environment can be changed within the portfile, i.e. include paths can be omitted. Look here : https://guide.macports.org/#reference.phases.configure (configure.env-delete). Otherwise I guess  it should be possible to just remove the previously installed file.

**Comment by egull** [comment]
It will reappear whenever you try to compile ALPS but have another ALPS in your system path.

Here's an idea: replace the #include<> with #include"" inside of ALPS. That way the local one will be searched first, even if there is a globally installed one around?

**Comment by aeantipov** [comment]
I agree, it is the best workaround

**Comment by galexv** [comment]
Something along these lines can be done. From [GNU CPP documentation](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html#Include-Syntax):

> `#include <file>`
This variant is used for system header files. It searches for a file named file in a standard list of system directories. You can prepend directories to this list with the `-I` option (see Invocation). 
> `#include "file"`
This variant is used for header files of your own program. It searches for a file named file first in the directory containing the current file, then in the quote directories and then the same directories used for `<file>`. You can prepend directories to the list of quote directories with the `-iquote` option.

The most portable way would probably be copy `config.hpp` from utilities to the current build directory; although, both icc and clang also have `-iquote` option, so it may be portable enough for our purposes.

Also, CMake has a mechanism of putting user include directories in front of the system include directories in the search path; the trick here is to convince CMake that `/opt/local/include` is the "system" search path.

**Comment by galexv** [comment]
It seems to be a an issue with ALPSCore and not with MacPorts, after all. It should pop up every time one has ALPSCore and, e.g., Boost installed under the same root directory (such as `/usr/local` or `/opt/local` or `~/.local`). For example, it can be reproduced on my Ubuntu Linux system this way:

```bash
 ## Fake installing Boost in a non system-wide dir:
$ root=/tmp/fakeroot
$ mkdir -p $root/{include,lib}
$ ln -s /usr/include/boost $root/include/
$ ln -s /usr/lib/*/libboost* $root/lib/
 ## Fake a previous "incompatible" installation of ALPSCore
$ mkdir -p $root/include/alps
$ echo '#error "This is a wrong config.hpp!" ' >$root/include/alps/config.hpp
 ## Configure ALPSCore to use Boost at $root
$ cd /where/your/build
$ cmake -DBOOST_ROOT=$root /where/alpscore/source
 ## The build will fail on "#error" directive when compiling archive component.
$ make
```

**Comment by galexv** [comment]
The fix seems to be working; the macport compilation went ok. Closing the issue.

**Comment by egull** [comment]
before you close, can you update and resubmit the port file?

**Comment by galexv** [comment]
That one is tracked by #252.
