### ISSUE TITLE
Parallel I/O with HDF5

### ISSUE THREAD

**Issue by jgreitemann** [ALPSCore/ALPSCore#256]
`alps::mcbase` saves the simulation to the HDF5 path `/simulation/realizations/0/clones/0`. I take it, the original intention was to save the checkpoints from all MPI processes to the same file rather than creating one file for each process as is currently the case in the Ising tutorial? The latter is slightly annoying on massively parallel systems which often impose a file limit, too. This is not a problem for me right now, though. I merely wanted to ask if you have any plans to support parallel I/O for `alps::hdf5::archive` since this is a major selling point for HDF5.

**Comment by galexv** [comment]
I do agree it is a good idea --- and yes,  in the case of a highly parallel computation having many small files in a directory may be a problem for something like Lustre. Let's have this feature in the wishlist!

**Comment by egull** [comment]
At this point we don't have capacity for this in the future, sorry. @jgreitemann , feel free to do it yourself if you have time/capacity.
