### ISSUE TITLE
Possible MPI deadlock

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#258]
Hi, let me discuss a possible MPI deadlock during the collection of measured results over processes.
My concern is about the implementation of alps::detail::mcmpiadapter_base::collect_results(names) const.
(around line 67 of mc/include/alps/mc/mpiadapter.hpp)

If a certain observable has not been measured for only some of MPI processes
, collective_merge will not be called from all MPI processes.
This results in a very silent deadlock.

I give a sample code at https://github.com/shinaoka/mpi_dead_lock ,
where the observables are measured only on the master process.

A solution is doing as follows. What do you think?
(i)  If the observable is measured on all the processes, we call collective_merge.
(ii) If the observable is not measured on any MPI process, we do not collect results.
(iii) [New] Otherwise, throw an exception.

**Comment by galexv** [comment]
Thanks for catching this --- and for the code testing for this!
I agree --- the most straightforward approach is to throw exception in this case (i think, it must be at 
https://github.com/ALPSCore/ALPSCore/blob/master/mc/include/alps/mc/mpiadapter.hpp#L76) ?

Do you have a fix ready? (If not, i can take care of this once i am back from SC16, on Friday).

**Comment by shinaoka** [comment]
Not yet. But, I will take care of this issue.

My idea is to collect "this->measurements[*it].count()" just below L69.
In the case of (iii), we throw exception immediately.
We proceed in the case of (i).
How about (ii)?
Should we throw exception, or just skip collective_merge?
I'd prefer the latter one.

**Comment by shinaoka** [comment]
I prepared a fix, and am writing a test for this.
I have a question about the testing framework of ALPSCore.
How can we run the tests with multi processors?
I tried "mpirun -np 2 make test" on my Mac,
but there seems to be another deadlock in the test mpi_utils_env.

**Comment by galexv** [comment]
Thanks for preparing the fix!
Making an MPI-aware test with GTest is a little of a multi-step process. For example, see an MPI test at 
https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/test/mpi_merge.cpp:

1. It has an explicit `main()` (https://github.com/ALPSCore/ALPSCore/blob/master/mc/test/sum_mpi.cpp#L137)
2. In `main()`, after initializing MPI environment, it  creates a local object of type `alps::gtest_par_xml_output`  and then calls this object with the rank, `argc` and `argv` (you need to include a header file `<alps/utilities/gtest_par_xml_output.hpp>`, see https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/test/mpi_merge.cpp#L16 . This is to make sure that GTest writes XML output to rank-specific files.
3. In the `CMakeLists.txt` file (see https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/test/CMakeLists.txt#L32) the MPI-aware test file should be added using `alps_add_gtest(${your_test_file} NOMAIN PARTEST)` (see https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/test/CMakeLists.txt#L44).
4. To actually run the test in parallel, one should use regular `make test` but set an environment variable `ALPS_TEST_MPI_NPROC` to the number of parallel processes; e.g. `ALPS_TEST_MPI_NPROC=2 make test` runs all MPI-aware tests with 2 MPI processes.
5. Also, it is always possible to run the test executable explicitly using `mpiexec`, e.g. 
`(cd build/mc/tests && mpiexec -n 2 mpi_dead_lock)`

Hope this helps. 

However, in my experience with OpenMPI,  an unbalanced broadcast may not result in a deadlock right away, but puts the MPI library in a confused state which would often result in a deadlock later on (as likely as not, in a destructor calling `MPI_Finalize()`!)   I wrote some rather simple "framework" to test specifically for unbalanced broadcast, but it is not polished at all and is used to test GF MPI code only: you can have a look at https://github.com/ALPSCore/ALPSCore/blob/master/gf/test/four_index_gf_test_mismatched_mpi.cpp#L52 and below, and at [mpi_guard.cpp](https://github.com/ALPSCore/ALPSCore/blob/master/gf/test/mpi_guard.cpp) and [mpi_guard.hpp](https://github.com/ALPSCore/ALPSCore/blob/master/gf/test/mpi_guard.hpp) in the same directory.

**Comment by shinaoka** [comment]
Thank you! I'll give it a try once I finish some other job. I'll keep you posted.

**Comment by galexv** [comment]
Fixed by pull request #259 (with minor changes by commit cc7fc3256ca).
Thanks @shinaoka !
