### ISSUE TITLE
Compilation of user code picks the wrong `alps/config.hpp` for CMake 3.7

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#262]
This is closely related to (closed) issue #255 .

When CMake 3.7 (and possibly an older CMake) is used, the user code may pick up the wrong `alps/config.hpp` --- for example, the one residing in the same directory as Boost, not the one found by `find_package(ALPSCore)`. The error is not observed with CMake 2.8.12.

The immediate reason for the problem is that CMake 3.7 considers ALPSCore include dir to be one of the "system" header directories, and therefore it has the same "search priority" as the Boost include dir. I am now looking at why CMake 3.7 does so.

**Comment by galexv** [comment]
The problem is that CMake considers interface include directories of imported targets to always be "system" directories (which seems to be contrary to documentation), so it looks to me like a bug in CMake. This behavior is observed since at least CMake 3.2.0, so if it is indeed a bug, no one else is bothered by it, so it is unlikely to be fixed. :( 

We have to look into workarounds.

**Comment by egull** [comment]
Rather than engineering a workaround, I would add a recommendation to the documentation stating that people should not install their ALPSCore in their system /boost path if they plan on having more than one ALPSCore.

**Comment by galexv** [comment]
If anyone is bitten by this bug, feel free to reopen.
