### ISSUE TITLE
Is it possible to load GF from HDF5 without constructing grids first?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#279]
Related to issue #277. As reported by Sergey (@iskakoff), there seems to be no (documented) way to read a GF from a file without constructing meshes first.

If such a way does exists, then it must be documented and tested (see issue #275).

**Comment by aeantipov** [comment]
I guess a code from here (https://github.com/aeantipov/gftools/blob/master/gftools/hdf5.hpp) can be adapted for that purpose : see load_grid_object() call. It does not require constructing the grids explicitly by a user, they are are constructed later by the method.

**Comment by iskakoff** [comment]
@aeantipov it based on c++11 variadic templates

**Comment by aeantipov** [comment]
I think it can be ported to ALPSCore gf. It basically reads the grids, construct a GF out of them and then reads the data.

**Comment by shinaoka** [comment]
I am writing toy python wrapper for alps::gf. Actually, the construction of GF objects is bit cumbersome. If GFs were default-constructible in C++ level, we would be able to construct a GF like this.
```
import alps.hdf5
import alps.gf
f = alps.hdf5.archive('gf.h5', 'r')
gf = alps.gf.MatsubaraGF()
gf.load(f, '/G_iw') 
```

**Comment by shinaoka** [comment]
What if we make Meshes and GFs default-constructible (in C++)? What (bad) side effects do you expect? It may be less fail safe because users may attempt to use an uninitialized object.

**Comment by galexv** [comment]
I am moving the discussion regarding default-constructing to issue #277.

**Comment by galexv** [comment]
Apparently it is now possible to default-construct a GF object and then load into it from HDF5, without constructing grids first.
