### ISSUE TITLE
Using Legendre basis in gf

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#281]
Is someone already working on the implementation of Legendre basis for gf?

**Comment by egull** [comment]
@iskakoff are you either using it or thinking of doing something?

**Comment by shinaoka** [comment]
If no one has a concrete plan, I will implement this functionality myself for ALPSCore! Besides, I am also interested in implementing a container based on an expansion of G(tau) in terms of a "numerical" orthonormal basis set on the imaginary-time axis.

**Comment by egull** [comment]
sounds good to me. Please go ahead – and keep us in the loop, so we can use your developments!

**Comment by shinaoka** [comment]
OK. I will keep you updated. Actually, a private version of our CT-HYB code replies on a numerical basis set rather than the Legendre basis.

**Comment by shinaoka** [comment]
It's done.
