### ISSUE TITLE
Restore clang (and Mac) test builds

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#283]
...either on cloudbees or on AWS. 
(Cf. issue #249)

**Comment by aeantipov** [comment]
I started using travis-ci lately. Seems very easy to configure (add 1 file to repo) and provides multiple builds with different environments including clang.
Here's a configuration that compiles alpscore (strip the unnecessary lines for other code): 
https://github.com/aeantipov/fk_mc/blob/master/.travis.yml

**Comment by galexv** [comment]
Aha. And it apparently supports Mac builds now: https://docs.travis-ci.com/user/osx-ci-environment
We should start using it.

**Comment by egull** [comment]
yes, but it does not do testing for closed source programs, which is another thing we really need. I propose to not switch to travis and stay with jenkins on AWS.
