### ISSUE TITLE
Random seed in Monte Carlo simulations

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#307]
I got some feedback from a user.
He ran our ALPSCore/CT-HYB several times by increasing the random seed one by one to estimate error values of Green's function in MPI calculations.
This will lead to a wrong estimate of error vars because we use the given "SEED" + I for process I.
https://github.com/ALPSCore/ALPSCore/blob/master/mc/include/alps/mc/mpiadapter.hpp#L37

Should we do something like this? 
   Base(parameters, 7*comm.size()*comm.rank())

Or, should we document it?

**Comment by egull** [comment]
I vote for documenting it more clearly. I don’t really see how we could change it in such a way that it is transparent what the seeds are on the non-master nodes (other than writing them down somewhere). Besides, the seeds increased by 1 make it easy to debug if something goes wrong. But it is a problem, I’ve seen that happen before.

Emanuel

**Comment by shinaoka** [comment]
Yeah, anyway, it should be documented for developers of applications depending the ALPSCore libraries. But let us think about users of these applications. They won't read our documents for sure. How about introducing one more argument to the construct of mcmpiadapter which specifies the step size (default value should be 1).

**Comment by shinaoka** [comment]
Yes, the fixed code does what I really  want! Closing...
