### ISSUE TITLE
Compilation of ALPSCore with IBM xlc++ (e.g. on UMich's "conflux")

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#312]
There is a number of problems, ranging from compilation failure to lack of optimization. Some of them can be addressed on our side.

1. Boost will not compile unless `-qnoxlcompatmacros` compiler flag is given.
1. Default `cmake` invocation that sets `CMAKE_BUILD_TYPE` to `RelWithDebInfo` results in unoptimized (equivalent to `-O0`, `NDEBUG` not defined)  build.
1. `xlc++` compalins about lost optimization opportunities.

Current workaround is to use `cmake -DCMAKE_CXX_FLAGS='-qnoxlcompatmacros -DNDEBUG -O2 -qmaxmem=-1'` , but we can detect the use of the IBM compiler in our CMake scripts and adjust the flags.

**Comment by galexv** [comment]
> 2. Default cmake invocation that sets CMAKE_BUILD_TYPE to RelWithDebInfo results in unoptimized (equivalent to -O0, NDEBUG not defined) build.

Ok, this seems to be no longer be true with xlc++ 13.1.4 and CMake 3.5.2. I see `CMAKE_CXX_FLAGS_RELWITHDEBINFO` set correctly to `-O2 -g -DNDEBUG`.

Still, '-qnoxlcompatmacros -qmaxmem=-1` is needed.

**Comment by galexv** [comment]
I leave it open until test failures (issue #313) is addressed; then it must be documented in Wiki.

**Comment by egull** [comment]
We can close this. The updated XLC works beautifully with ALPSCore, out of the box, with no added compile flags.
