### ISSUE TITLE
Several tests fail on IBM Power8 when compiled with xlc++

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#313]
The following tests fail:

* `mean_err_count` : numerical discrepancy about 2.E-8 in the mean value, 2.E-7 in the error value for float no-binning accumulators with linear data;
* `save_load2`: HDF5 error when testing `long double` accumulators, see issue #290;
* `custom_type`: HDF5 error when testing user-defined type accumulators, see issue #290;
* `file_read`: SIGSEGV when testing `param.WrongValuesInFile`
* `sum_mpi`: hangs indefinitely, apparently unable to detect that the simulation is over, because scheduler does not think that a check is pending, ever;
* `mesh_test`: default-constructed mesh does not throw an exception on save()

Out of these, `sum_mpi` is the most puzzling as of now; it looks like a lot of code, including condition checks, is optimized out, as if the compiler determined that those condition variables cannot ever change.

**Comment by galexv** [comment]
> Out of these, sum_mpi is the most puzzling as of now

Maybe the same as issue https://github.com/ALPSCore/ALPSCore/issues/322#issuecomment-308554348

**Comment by egull** [comment]
I tried to run this on ibm with xlc, running into problems with boost PP right at the start of the compilation (file utilities/src/gtest_par_xml_output.cpp). Just to confirm that these problems didn't go away in the mean time.

**Comment by galexv** [comment]
That particular problem is documented as issue #312

**Comment by egull** [comment]
Jia, you're on Conflux... could you please have a look if this works with xlc and give a progress report?

**Comment by katherlee** [comment]
Sure, I'll take a look.

**Comment by katherlee** [comment]
I am getting the following error during CMake:
```
CMake Error at common/cmake/ALPSCommonModuleDefinitions.cmake:187 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "XL"

  version 13.1.4.
```

@galexv is there a quick fix I can get around it with?

**Comment by katherlee** [comment]
From CMake documentation:

> CMake is currently aware of the C++ standards and their associated meta-features (e.g. `cxx_std_11`) available from the following compiler ids as of the versions specified for each:
>
>    Cray: Cray Compiler Environment version 8.1 through 8.5.8.
>    PGI: PGI version 12.10 through 17.5.
>    XL: IBM XL version 10.1 through 13.1.5.

It looks like CMake doesn't know about any c++ compiler features of XL except for the meta-features like `cxx_std_11`.

**Comment by galexv** [comment]
A quick workaround would be to configure ALPSCore with `-DALPS_CXX_STD=custom` and make sure that  the relevant C++-11 compiler options are set via `-DCMAKE_CXX_FLAGS`. The client code might also have to set `-DALPS_FORCE_CXX_STD=custom`.

Cross-reference: #452 .

**Comment by katherlee** [comment]
Thanks @galexv, it works. Now I get the following error related to Eigen:
```
In file included from /gpfs/gpfs0/groups/gull/lijiax/src/alpscore-fork/utilities/test/tensor_test.cpp:10:
In file included from /gpfs/gpfs0/groups/gull/lijiax/src/alpscore-fork/utilities/include/alps/numeric/tensors/tensor_base.hpp:17:
In file included from /gpfs/gpfs0/groups/gull/lijiax/src/alpscore-fork/build-xlc/eigen/000unpack/eigen-eigen-5a0156e40feb/Eigen/Core:376:
/gpfs/gpfs0/groups/gull/lijiax/src/alpscore-fork/build-xlc/eigen/000unpack/eigen-eigen-5a0156e40feb/Eigen/src/Core/arch/AltiVec/PacketMath.h:1025:13: error: cannot initialize a variable of type 'Packet2bl'
      (aka 'Packet2ul') with an rvalue of type '__vector __bool unsigned long long' (vector of 2 'unsigned long long' values)
  Packet2bl mask = vec_cmpeq(reinterpret_cast<Packet2d>(select), reinterpret_cast<Packet2d>(p2l_ONE));
            ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This might be related to the vectorization options for XL on Power8, but I am not exactly sure. The following is my compiler flags:
``` -qlanglvl=extended0x -qnoxlcompatmacros -DNDEBUG -O2 -qmaxmem=-1  -qarch=pwr8```

**Comment by egull** [comment]
all tests pass on conflux with the following modules:

module load compilers/ibm-xlc/16.1.0
module load cmake/3.5.2

module load openmpi/1.10.3/ibmxl/16.1.0
module load hdf5/1.10.0/xlc-xlf/latest

export BOOST_ROOT=/gpfs/gpfs0/software/rhel72/packages/boost/1.61.0-xlcpp-13.1.4

export CC=xlc
export CXX=xlc++
cd target
sh ../common/build/build.jenkins.sh --cmake-flags "-DEIGEN3_INCLUDE_DIR=$HOME/software/Eigen_3.3.4"
