### ISSUE TITLE
ALPSCore does not compile with Boost 1.64 (fix is simple)

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#314]
...because `boost::ublas` uses `boost::serialization::make_array` and the latter has been moved to another header (`boost/serialization/array_wrapper.hpp`). 

Explicitly having  `#include <boost/serialization/array_wrapper.hpp>` makes it compile, but (strictly speaking) re-introduces explicit dependence on `boost::serialize`.

I am marking it as a bug for the time being, but we really have to get rid of `boost::ublas` (issue #37) and replace it with Eigen as discussed earlier.

**Comment by egull** [comment]
depends on #37 and #157

**Comment by galexv** [comment]
The issue is not there with Boost 1.65.1

**Comment by galexv** [comment]
Going to get rid of ublas in the code.
