### ISSUE TITLE
Suspected too high memory consumption when doing vector arithmetic

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#317]
Markus (@mwallerb) suspects that there is too much memory consumption when operating on large vectors due to creating unnecessary temporaries in vector arithmetic.

**Comment by egull** [comment]
I'm not surprised. Especially with the full and log binning observables. No
binning should be fine but of course has no error analysis...

**Comment by mwallerb** [comment]
Fixed in the ALEA library (commit 5bfd7b61) by using in-place accumulation with `alps::alea::computed`.
