### ISSUE TITLE
Are "large" (fragmented) HDF5 files still supported?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#319]
In `hdf5::archive` constructor  it is possible to pass archive creation/opening flag `"l"` which uses [HDF5 "family" driver](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetFaplFamily); this requires use of printf-style format symbol (`%d`) in file names, see https://support.hdfgroup.org/HDF5/doc/TechNotes/BigDataSmMach.html .

This feature is not tested in ALPSCore any more (the test is marked "obsolete"). Also, [the corresponding part of `archive.cpp` code](https://github.com/ALPSCore/ALPSCore/blob/b3a4e4f4efb9203350284ff4799c14a43534d320/hdf5/src/archive.cpp#L264) contains a bug. Moreover, on reasonable (64-bit) systems there is little need for this driver, as maximum file size is likely quite large.

Should we explicitly drop support for this feature?

**Comment by egull** [comment]
I think so. No need to carry something around that we know is buggy.

**Comment by galexv** [comment]
Support for the split-files removed, so the above-mentioned bug is not pertinent anymore. Closing the issue.
