### ISSUE TITLE
Test failures after merging de-boosted branch

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#322]
WTH?? Some errors creeped in during merge??
Looking at it...

**Comment by galexv** [comment]
Seems nothing more than a type in a long-to-run test. Fixed.

**Comment by egull** [comment]
No, not good. I get additional failures:
[ RUN      ] CheckScheduleTest.UseFakeTimer
/Users/egull/ALPSCore/mc/test/check_schedule.cpp:70: Failure
Value of: checker.pending()
  Actual: false
Expected: true
[  FAILED  ] CheckScheduleTest.UseFakeTimer (1 ms)
[----------] 2 tests from CheckScheduleTest (1 ms total)

In addition, I the reduce and sum_mpi tests do not terminate.

**Comment by egull** [comment]
yes, this seems to have fixed #322 .
