### ISSUE TITLE
[hdf5] Make signatures of save()/load() consistent throughout the library

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#337]
I am currently trying to write a GF class, which is derived from `two_index_gf<std::complex<double>, my_mesh, my_mesh>`.

Following a [tutorial](https://github.com/ALPSCore/ALPSCore/blob/master/tutorials/hdf5/custom_hdf5/main.cpp#L73), I defined a couple of methods in `my_mesh`,
```c++
    void save(alps::hdf5::archive& ar) const;
    void load(alps::hdf5::archive& ar);
```
`my_mesh` can now be successfully saved/loaded to/from an HDF5 archive.

When I try to save the GF, I get the following compilation error:
```
/include/alps/gf/gf.hpp:445:32: error: too many arguments to function call, expected single argument 'ar', have 2 arguments
                mesh1_.save(ar,path+"/mesh/1");
```

Does it mean `my_mesh::save()` must take two arguments?
If so, what is the meaning of the second argument? Is that path evaluated w.r.t. the context set in `ar`? Is there a difference between absolute and relative paths?

**Comment by krivenko** [comment]
After a brief discussion we concluded that the signature of `save()`/`load()` should be consistent throughout the library. My personal preference is to leave one argument everywhere.

This is a long-term task as it can potentially break existing codes.

**Comment by krivenko** [comment]
It turns out that `alps::hdf5::archive::operator<<()` and `alps::hdf5::archive::operator>>()` always call the single-argument versions of `save()`/`load()`.

**Comment by aeantipov** [comment]
I think this also applies here - load() doesn't allow to construct an object from archive, i.e. a default constructor is needed for every object.

**Comment by galexv** [comment]
The fix is ready, upload pending completion of tests.

**Comment by krivenko** [comment]
> I think this also applies here - load() doesn't allow to construct an object from archive, i.e. a default constructor is needed for every object.

This is another issue that has to be addressed. But I think it deserves a dedicated discussion.

**Comment by krivenko** [comment]
It looks like I still need both versions of `load()`/`save()` in my mesh. Is this the intended resolution of the issue?

**Comment by galexv** [comment]
> It looks like I still need both versions of load()/save() in my mesh. Is this the intended resolution of the issue?

Ah, i see. If this is the issue, then we can get rid of 2-argument save/load in meshes altogether (i do not think they are used "externally" in any way).

**Comment by galexv** [comment]
Thanks Igor (@krivenko)!
