### ISSUE TITLE
[hdf5] Reading a list of fixed strings

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#341]
Related to this issue #332 

When we write a list of strings to a HDF5 with h5py,
it seems that the data are stored as fixed-size strings.
But, ALPSCore hdf5 libraries do not support "load" of this data type.

Here is my test.
https://github.com/shinaoka/ALPSCoreTests/tree/master/str_vec_hdf5

We can reproduce the error as follows.
> python string_vec.py 
> ./build/simple_hdf5                                                     
str: A
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: multidimensional dataset of fixed string datas is not implemented (/str_vec)

Is it technically difficult to support this feature?

**Comment by galexv** [comment]
I will look at it shortly.

**Comment by galexv** [comment]
@mwallerb Markus, in fact we discussed it recently and the solution (on Python side) seemed simple. Do you mind taking over this?

**Comment by egull** [comment]
@shinaoka did this work the way Markus proposed? Do you have a solution? Do we still have a need for this?

**Comment by shinaoka** [comment]
OK, I confirmed the following code works both for Python 2 and 3.

https://github.com/shinaoka/ALPSCoreTests/blob/master/str_vec_hdf5/string_vec.py
