### ISSUE TITLE
Suggest compiling ALPSCore by g++ with `-Weffc++`

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#344]
The [`-Weffc++` flag](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html) activates warnings of violations of "Effective C++":

> -Weffc++ (C++ and Objective-C++ only)
> Warn about violations of the following style guidelines from Scott Meyers’ Effective C++ series of books:
> 
> * Define a copy constructor and an assignment operator for classes with dynamically-allocated memory.
> * Prefer initialization to assignment in constructors.
> * Have `operator=` return a reference to `*this`.
> * Don’t try to return a reference when you must return an object.
> * Distinguish between prefix and postfix forms of increment and decrement operators.
> * Never overload `&&`, `||`, or `,`.

For example, a bug mentioned at https://github.com/ALPSCore/ALPSCore/issues/322#issuecomment-308554348 could have been caught by this setting (even `valgrind`, although it detects the use of an uninitialized variable, does not pinpoint the origin of the problem). (Issue #313 may be related)

A trial run compiling a subset of files generated warnings that warrant a closer look; this issue will serve as a placeholder to do it in a near future.

**Comment by egull** [comment]
should be put as a hint into developer docs

**Comment by galexv** [comment]
Added a phrase to [dev docs](https://github.com/ALPSCore/ALPSCore/wiki/Developer-guidelines).
