### ISSUE TITLE
Add a continuously-tested "development" branch to the repo

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#345]
Currently, changes have to be merged into master to be tested by CI. It may be worth to have a separate development branch, which should be also auto-tested, and from which the merges are done after some review, via pull-requests.

**Comment by egull** [comment]
good idea. And easy to implement with Jenkins on AWS.

**Comment by galexv** [comment]
Added "devel" branch: https://github.com/ALPSCore/ALPSCore/tree/devel

Set up Cloudbees/Jenkins builds: [quick-build](https://alpscore.ci.cloudbees.com/job/alpscore-devel-fedora17_boost-1.60.0_hdf5-1.8.13_openmpi-1.10.1_quickbuild/) and [long-test](https://alpscore.ci.cloudbees.com/job/alpscore-devel-fedora17_boost-1.60.0_hdf5-1.8.13_openmpi-1.10.1_longtest/).

**Comment by galexv** [comment]
It seems to be working, so i am closing it.
