### ISSUE TITLE
Explicit versioning of ALPSCore installation

### ISSUE THREAD

**Issue by iskakoff** [ALPSCore/ALPSCore#347]
Recently we have changed the structure of hdf5 representation for parameters that broke several codes that was based on the previous implementation. It's clear that some other functionality we do have right now will evolve in future and probably it will not be compatible with what we have right now. 
And it will bring us back to a set of broken codes. I've try to find any information about ALPSCore release that is stored either in cmake files or in some header files (like it's don in Eigen) so I can check the installation version I want to use and did not find anything.

I suggest to introduce the versioning on the CMake level, so users will be able in their codes to specify the major and minor versions (or range of versions) of ALPSCore they are going to use, and in case of incompatibility of new functionality in future they will be able to simply resolve it by using proper major version in the find_package script. This will at least resolve some problems with incompatibility.

**Comment by galexv** [comment]
Good idea. I was thinking about the same for some time now, that's it's time to introduce an explicit versioning.
