### ISSUE TITLE
clang address sanitizer for tests

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#35]
Make a jenkins test that compiles and runs with the clang address sanitizer to detect memory problems (factor of two).

**Comment by galexv** [comment]
Just a comment.

clang **memory sanitizer** (check access to uninitialized memory) requires *all* libraries to be compiled with the memory sanitizer instrumentation, including libc++ (see https://code.google.com/p/memory-sanitizer/wiki/LibcxxHowTo).

clang **address sanitizer** (check out-of-bounds access to heap, stack and globals) does not seem to require recompilation of all libraries.

It is also possible to use gcc STL debug mode (https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode.html) to catch out-of-bound access to STL containers (although Boost has to be recompiled). I successfully caught some bugs (issue #87) this way.

**Comment by aeantipov** [comment]
Can one do a debug mode + tracing to check for memory leaks?

**Comment by egull** [comment]
ok. Because the clang and gcc on jenkins are too old (3.0 instead of 3.1, 4.7 instead of 4.8) we have no way of running this in the default cloudbees setup. @gcarcassi : do you have any idea if we can make them update compilers or if we're allowed to install our own packages? Otherwise I'd close this as 'wontfix' or, again, we can delegate it to one of our external builders.

**Comment by egull** [comment]
OK, we have one up and running, using the svn version of clang/llvm
