### ISSUE TITLE
Accumulator Revamp

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#351]
Markus' accumulator revamp

**Comment by galexv** [comment]
Do we intend to retain the existing interface, including the separation of `accumulator`s and `result`s? Are we revamping only the implementation?

**Comment by mwallerb** [comment]
I'm not sure. I don't think the split of `accumulator` and `result` is particularly useful, and I think the current tag-inheritance structure pretty much locks us in in the sense that we cannot perfectly reproduce the API with a different -- and IMHO potentially more maintainable -- setup.

Emanuel's and my proposal would be to introduce a new library, `alps::alea` (working title), with a new setup of classes, but for the "simple" use case make them work exactly the same, such that in most cases one basically just has to switch out class names. Then we slowly phase out the current library.

**Comment by egull** [comment]
The split between accumulators and results was originally done to facilitate transfer of data over the network. We'll need to discuss how exactly we're going to do network operations / collective calls with the revamped version once you're back.

**Comment by mwallerb** [comment]
ALEA is now feature-complete. Closing.
