### ISSUE TITLE
`hdf5::archive` needs refactoring

### ISSUE THREAD

**Issue by mwallerb** [ALPSCore/ALPSCore#356]
From a quick glance through [/hdf5/src/archive.cpp](https://github.com/ALPSCore/ALPSCore/blob/master/hdf5/src/archive.cpp):

- [x]  `ALPS_HDF5_WRITE_VECTOR` is a 180-line (!) macro (!!)
- [x]  `ALPS_HDF5_READ_SCALAR_*_HELPER` even mess up the control flow (they expect certain brace structures) and thus thoroughly break the human parser. I'm surprised there is no `return` in there for extra confusion.
- [ ]  The code does not have a single line of documentation in there (I grepped!)
- [ ]  The `archivecontext` [PImpl](https://en.wikipedia.org/wiki/Opaque_pointer) does an excellent job of hiding useful features, such as mem-mapping of dataspaces.

**Comment by egull** [comment]
No capacity to do this in the near term, sorry. I will close this, we'll reopen if we get capacity to rewrite archive.
