### ISSUE TITLE
[params] Access to parameter metadata

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#359]
I am about to write a function that takes an instance of `alps::params`, iterates over all parameters, and adds them to a `boost::program_options::options_description` object. Therefore, access to the following information about a parameter is required:

1. Parameter type;
2. Parameter description;
3. Default value of the parameter.

Point 1 implies that some sort of visitation is required.

How can I do this at the moment? Will I have to change my code once de-boostification of the parameters is done?

**Comment by galexv** [comment]
At the moment it's possible either by writing a corresponding visitor, or, maybe, by accessing internals of the parameter object, because it uses `program_options` in the current implementation.

The new version of parameters will necessitate reimplementation. I can take care of that, or we can meet on Monday and discuss. Can you think of a convenient interface without explicit dependency on boost:: program_options? Maybe, a friend class? Or a class or function templated over T where T can be options_descriptions?

**Comment by galexv** [comment]
Another option would be to provide some `parameter_visitor` API,  to have `operator<T>(name, value)` called for every parameter, passing the type `T`, the name and the value  (I guess it's what you had in mind too). Would it be a better option? It looks, at least, more universal.

**Comment by krivenko** [comment]
`boost::apply_visitor()` and friends are parts of the variant library, which is header-only. Currently, `option_type` uses visitation internally, but does not expose the interface to user. I think, this is very easy to fix. Moreover, retaining the same interface in the new version should not be too difficult either.

**Comment by krivenko** [comment]
> Another option would be to provide some parameter_visitor API, to have operator<T>(name, value) called for every parameter, passing the type T, the name and the value (I guess it's what you had in mind too).

Yes, this is what I meant. For an object `op` of type `option_type` I should be able to write
```
boost::apply_visitor(my_visitor(), op);
```
That said, I still cannot see what to do about points 2 and 3. Would need to read `option_description_type.hpp` first...

**Comment by galexv** [comment]
I see that as of commit https://github.com/CQMP/InchwormHPX/commit/b23525f9e5253266a5e80753ec85c68d1e526c9d `apply` and `foreach` free functions are not used (please correct me if i am missing something!).

In the revised design of `alps::params` parameters do not have any default value as an attached attribute; instead, if at the moment of parameter definition the value of parameter is not supplied via a command line or INI file, it acquires the supplied default value. After a parameter is defined and has acquired a value, it is not possible to recover the default. 

I could make the default values a part of the object state, but i currently do not see a use for them other then `apply` and `foreach`, and having defaults around complicates serialization.

In the new design, dictionary objects (and parameters, being a derived class) can be visited via [`apply_visitor(visitor_functor, dict_iterator)`](https://github.com/ALPSCore/ALPSCore/blob/newparam-deboost/params/include/alps/dictionary.hpp#L104) call; everything else can be built on top of it, including `apply` and `foreach`. I understand that visitation syntax may be a bit unwieldy, so i am open to suggestions for a more narrow purpose  oriented interface. Perhaps, some kind of interface to `boost::program_options`?

As of now it is possible to access parameter metadata via `apply_visitor()` call; so, i am closing this issue.
