### ISSUE TITLE
[new params] Make help message look better

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#370]
...which necessitates better approach to represent types internally and on print (see discussion at PR https://github.com/ALPSCore/ALPSCore/pull/363#discussion_r149526529).

**Comment by galexv** [comment]
Related issue #143.

**Comment by galexv** [comment]
See also issue #240

**Comment by ryanlevy** [comment]
Can there be better output for booleans? As per #168, a bool param cannot be set as 0. However the output from a help message has `(default value: 0)` which makes things very confusing.

**Comment by galexv** [comment]
Continued in issue #399
