### ISSUE TITLE
Does not compile cleanly with `-Wall`

### ISSUE THREAD

**Issue by mwallerb** [ALPSCore/ALPSCore#375]
ALPSCore emits a huge strings of warnings with `-Wall`, particularly in the HDF5 and the accumulators modules.

This makes it very ugly to enable `-Wall` by default (ideally also `-Wextra`, but I'm not that `-pedantic`).  By disabling `-Wall`, however, we hide a lot of potential problems in the development stage.  Also, it is just not good style to have warning-ridden code.

**Comment by galexv** [comment]
Related: #344

**Comment by mwallerb** [comment]
Guys, can we please enable `-Wall` by default? -- I feel like for every warning I fix some new code introduces 2 new warnings.  I feel like a 21st century serious scientific code should compile more or less cleanly.

**Comment by egull** [comment]
Wall does very different things on different compilers. We can enable it
for gcc and clang but please not for Intel!

**Comment by galexv** [comment]
If it was my merge, i apologize.
I share the same feeling, but having `-Wall` by default does not always help by itself: unless all warnings are eliminated, it's not obvious that i now have. e.g., 11 warnings instead of 10 that was before my patch.

**Comment by mwallerb** [comment]
@galexv that was more of a *weltschmerz* than directed at anybody, sorry if it came across as mean :-)
Anyway, you're probably right -- warnings are too uneven across compilers to enable all of them by default.

**Comment by galexv** [comment]
@egull @mwallerb Shall we close this? TravisCI now runs with `-Wall -Wno-missing-braces -Wmissing-field-initializers -Werror`.

https://github.com/ALPSCore/ALPSCore/blob/2bf63e72dbe2a09f5a1c0dc06b328d73b5e41aa7/common/build/build.travis.sh#L37

**Comment by egull** [comment]
Markus @mwallerb , I defer to you.

**Comment by mwallerb** [comment]
@galexv @egull  I think so.  And now CI will bug us if it ever comes up again.
