### ISSUE TITLE
Builds in debug mode when CMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by yurivict** [ALPSCore/ALPSCore#389]
With ```CMAKE_BUILD_TYPE=Release``` getting these warning:

```
#warning "NDEBUG is not defined in GF. This leads to very slow code. Define ALPS_GF_DEBUG to suppress this warning"
 ^
```

CMAKE_BUILD_TYPE should fully determine debug flags.

**Comment by galexv** [comment]
@yurivict I cannot reproduce this behavior on my Linux box with CMake 3.1 and gcc 5.4. Default CMake flags for `CMAKE_BUILD_TYPE=Release` already include '-DNDEBUG', and ALPSCore's cmake script just adds `-DBOOST_DISABLE_ASSERTS`. I do not observe any warnings regarding potentially slow code.

That's said, FreeBSD and Ubuntu Linux default CMake settings might differ. Although it's easy to patch this particular problem (simply by adding "-DNDEBUG" explicitly to compiler flags in our cmake scripts), i'd like to get to the root of it. Unfortunately, we currently do not have access to a FreeBSD box. Could you please generate a fresh `CMakeCache.txt` (by running  `cmake -DCMAKE_BUILD_TYPE=Release /path/to/ALPSCore_source`) and attach it here? Thanks!

**Comment by egull** [comment]
This is fixed.
