### ISSUE TITLE
Missing -lexecinfo

### ISSUE THREAD

**Issue by yurivict** [ALPSCore/ALPSCore#390]
I have to add `LDFLAGS+=-lexecinfo` because it is otherwise missing.

Found in the FreeBSD port.

**Comment by galexv** [comment]
Thanks for the tip.

**Comment by egull** [comment]
Hi @yurivict ,
we don't have the capability to test FreeBSD. Would you be able to provide a patch for us?

**Comment by egull** [comment]
Can't fix this without more info. Please reopen once we have more info.
