### ISSUE TITLE
params initialization error

### ISSUE THREAD

**Issue by ryanlevy** [ALPSCore/ALPSCore#398]
When attempting to set a parameter with the wrong data type, an error prints out `Attempt to read uninitialized value`
Here is a simple use case:
_main.cpp_
```c++
alps::params par(argc, argv);
par.define<int>("count", 0, "Number of interconnected elements");
int count=par["count"];
std::cout<<"The count is "<<count<<std::endl;
```
_in.ini_
```
count=st
```
or `./main --count=st`
Error:
```
$ ./main in.ini 
libc++abi.dylib: terminating with uncaught exception of type alps::params_ns::exception::uninitialized_value: Key 'count': Attempt to read uninitialized value
```
I came across this because of #168. If you set a bool as `0` in an ini file, this is the resulting error, even if defaulted.

**Comment by galexv** [comment]
The invalid format should be caught by:
```c++
alps::params par(argc, argv);
par.define<int>("count", 0, "Number of interconnected elements");
if (p.has_missing(std::cerr)) return; // Check for missing/invalid format and print them
/* Alternatively: 
if (p.has_missing()) { std::cerr << "Missing/invalid params!"; return; }
if (!p.ok()) { std::cerr << "Missing/invalid params!"; return; }
*/
int count=par["count"];
std::cout<<"The count is "<<count<<std::endl;
```
This should be better documented, i guess. :)

**Comment by ryanlevy** [comment]
Ah I see! Works exactly as I wanted already. 

Could we then get the [comment here](https://github.com/ALPSCore/ALPSCore/blob/master/tutorials/params/ini_params/main.cpp#L71) changed to say something about incorrect type please?
