### ISSUE TITLE
problem with forgotten inline in dict

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#402]
this leads to problems in a different part of the code: forgotten inline in dict_value_impl.hpp line 24.

[ 43%] Building CXX object src/util/CMakeFiles/dos2gf.dir/dos2gf.cpp.o
cd /Users/egull/Projects/Inchworm_legion/build/src/util && /opt/local/bin/mpicxx-openmpi-clang39  -DBOOST_DISABLE_ASSERTS -DHPX_DISABLE_ASSERTS -I/Users/egull/software/hpx_dec1_17/include -I/Users/egull/software/hpx_dec1_17/include/hpx/external -I/Users/egull/software/boost_1_65_1/include -isystem /opt/local/include -isystem /opt/local/include/eigen3 -I/Users/egull/Projects/Inchworm_legion/src/. -isystem /opt/local/include/openmpi-clang39 -isystem /Users/egull/ALPSCore/install/include  -O3 -DNDEBUG -DBOOST_DISABLE_ASSERTS -O3 -DNDEBUG   -std=c++11 -std=c++11 -o CMakeFiles/dos2gf.dir/dos2gf.cpp.o -c /Users/egull/Projects/Inchworm_legion/src/util/dos2gf.cpp
In file included from /Users/egull/Projects/Inchworm_legion/src/util/dos2gf.cpp:16:
In file included from /Users/egull/Projects/Inchworm_legion/src/util/../gf.hpp:3:
In file included from /Users/egull/Projects/Inchworm_legion/src/./gf/branch.hpp:15:
/Users/egull/Projects/Inchworm_legion/src/./gf/../utility.hpp:79:43: error: inline declaration of 'operator<<' follows non-inline
      definition
template<typename T> inline std::ostream &operator<<(std::ostream &os, std::vector<T> const &v) {
                                          ^
/Users/egull/ALPSCore/install/include/alps/./params/./dict_value_impl.hpp:24:19: note: previous definition is here
    std::ostream& operator<<(std::ostream& strm, const std::vector<T>& vec)
                  ^

**Comment by egull** [comment]
fixed by commit d65153a3

**Comment by egull** [comment]
...oops, that didn't fix it. Working on it.

**Comment by egull** [comment]
looks like this operator<< is hidden deep within boost variant calls. Do you know how to fix, @galexv?

**Comment by galexv** [comment]
Looking at it.
Strictly speaking,  dictionary does not need streaming operator for vectors, I am going to get rid of it.

**Comment by egull** [comment]
confirmed that it is fixed.
