### ISSUE TITLE
[params] help_requested() always returns false if no description is present

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#405]
https://github.com/ALPSCore/ALPSCore/blob/678a1d86eaa1db5676ea124f53c884ec6c0f866b/params/include/alps/params.hpp#L211

Why does one need to first call `description()` before using `help_requested()`? 
Even if there is no description string attached to the `params` object, it still makes sense to print descriptions of the options.

**Comment by galexv** [comment]
Hmm, the intention here was that if `description()` has not been called, the user does not want to have `--help` option defined (as we once discussed). And if the option is not defined, the help cannot be requested. 
But i see that user can anyway assign `p["help"]=true` to force "help request", and, moreover, it's useful to have a method `print_help(std::ostream&)` to get help with option descriptions unconditionally (e.g., after checking for missing parameters).
I'll fix that shortly.
