### ISSUE TITLE
Mesh MPI bugs

### ISSUE THREAD

**Issue by iskakoff** [ALPSCore/ALPSCore#407]
I have question. In all greens function mesh classes during broadcast we check that mesh is not empty.
But from my point of view, this does not make any sense for any process except the root one.

That is the whole point of broadcast, as far as I understand it. We do some work on root, like init GF, assign meshes and what ever, and then we broadcast it to everyone.

What was the reason in current implementation to check for emptiness on every process?
Or it is a legacy part that came from the time where GF was not default-constructible?

**Comment by egull** [comment]
Yes, I think this is legacy code. At the time I think we didn't even broadcast the meshes and you had to provide initialized meshes with the right size.

**Comment by galexv** [comment]
I believe the reason was that initially meshes were not default-constructible; when def ctor was added, the checks verifying mesh validity were simply added everywhere, and then removed where they are not necessary. Apparently, the latter did not happen in all places. :)

**Comment by iskakoff** [comment]
Here is a list of thing that I will fix:
1. Matsubara Mesh does not broadcast statistic
2. Matsubara Mesh does not check for positivity of the mesh during broadcast
3. Matsubara Mesh offset is not broadcasted
4. Matsubara Mesh offset is never updated (even during read from hdf5, that will lead to wrong behaviour for default constructed mesh)

**Comment by iskakoff** [comment]
fixed in #408
