### ISSUE TITLE
[cmake] libiniparser not exported

### ISSUE THREAD

**Issue by kleinhenz** [ALPSCore/ALPSCore#413]
On the current master, setting `ALPS_BUILD_TYPE="static"` causes a cmake error:

`CMake Error: install(EXPORT "alps-params" ...) includes target "alps-params" which requires target "libiniparser" that is not in the export set.`

It seems that `target_link_libraries(${PROJECT_NAME} PRIVATE libiniparser)` only affects transitive usage requirements and does not actually merge `libiniparser` into `alps-params`. It seems the way to accomplish that is through an explicit call to `libtool` (see [this](https://stackoverflow.com/questions/36181626/cmake-linking-to-static-internal-library-without-exporting-it) answer on stackoverflow). I think it would probably be easier/less hacky to just export libiniparser.

**Comment by galexv** [comment]
I believe i solved this particular issue, but i cannot hammer anything into compiling statically with ALPSCore on my laptop, so i cannot verify yet. Working on it...

**Comment by galexv** [comment]
It looks like:
1. Problem with a static linking on some systems is a separate issue
2. The solution for libiniparser does not work in CMake 3.1 because of a misfeature that was quietly fixed later (do not see anything relevant in changelogs, but it works in 3.5.1). I will work around it.

**Comment by galexv** [comment]
@kleinhenz Could you check if it works for you now?

**Comment by kleinhenz** [comment]
yeah that fixed it for me. thanks!

**Comment by galexv** [comment]
My pleasure. :) Closing now.
