### ISSUE TITLE
[params] Backward compatibility of subsubsections

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#414]
After playing around with the latest version in master branch,
I've found several problems.

An example is in https://github.com/shinaoka/alpscore-bug/tree/master/ini_params_hierarchical.

You may run the example like this:
```
ini_params configurationA.ini
```

After all, there are two problems.
The new library does not understand

```
[sectionA.subsectionA]
count2=1
```

This style worked for the old library and is popular for CT-HYB users (since the tutorials of CT-HYB are written in this style).
The new library should warn when this style is used.
Otherwise, default values are used unintendedly.

The segmentation fault may be a bug.

**Comment by galexv** [comment]
The root of the problem is that iniparser library assumes that section names do not contain dots.
That's why it:
1.  does not recognize keys in section `[section.with_dot]` (because it does not appear in the list of sections)
2. fails if there is also a section `[section]` (because it has a key `section.with_dot`, but this key does not have an associated value, it is `NULL`)

We are actually going to replace the iniparser library once we switch to C++11. 
I will see: if there is no quick workaround, i will implement throwing an exception if a section with a dot is encountered.

**Comment by shinaoka** [comment]
Thank you.
Throwing an exception may be enough for the moment because we're going to switch to C++11.

BTW, is there any way to check if an "undefined" key exists in an ini file?
For example, if we define the key "N_MATSUBARA" in our client code,
an user may write "NMATSUBARA" in an ini file mistakenly.
I want to detect such mistake in my client code.

**Comment by iskakoff** [comment]
@shinaoka in old params there was a method "exists" which can be used to check this. 
It seems it disappears in new params

**Comment by galexv** [comment]
@shinaoka  @iskakoff Actually, the method is alive and well, it's in the parent `dictionary` class; i am not sure, though, that it is what Hiroshi needs.

The relevant methods may be `exists()`, `has_missing()`, `has_unused()`, and `supplied()`; my guess is `supplied()` is the closest to what is wanted?

```c++
alps::params p(argc,argv);

// Something like this:
p.define<int>("N_MATSUBARA", "Number of Matsubara frequencies or other relevant description");

// Then:
// (We use `throw runtime_error` here which may be a bit harsh --- it's for the sake of example only)
if (!p.exists("N_MATSUBARA")) throw runtime_error("N_MATSUBARA is not provided");
if (!p.exists<int>("N_MATSUBARA")) throw runtime_error("N_MATSUBARA is not integer"); // This is not possible with the `define()` as above
if (!p.supplied("N_MATSUBARA")) throw runtime_error("N_MATSUBARA is not supplied via program args or INI file");

// This may be useful: 
if (p.supplied("NMATSUBARA")) throw runtime_error("NMATSUBARA is supplied, did you mean N_MATSUBARA?");

if (has_missing(stderr)) throw runtime_error("There are missing parameters");
// This is also of some relevance:
if (has_unused(stderr)) throw runtime_error("Some parameters are supplied but never defined by the program, possibly misspelled?");
```

**Comment by shinaoka** [comment]
Thanks!
has_unused() seems to be the right one.

**Comment by galexv** [comment]
@shinaoka Hiroshi, could you please verify that the fix works for you?
