### ISSUE TITLE
Demo test for python

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#43]
py_test --junitxml=path should give xmls. Write and parse a demo test for python.

**Comment by galexv** [comment]
@aeantipov: Andrey, could you provide some Python examples --- how do you use Python module? (We are anyway separating it, as per #121).

**Comment by aeantipov** [comment]
Ok, here we go - connsider it as a sketch. The idea is to run your code from python directly. 
```python
import my_awesome_module as m 
params = dict()
params["chicken"] = 1
m.solve(params)
```
The c++ code does smth like
```c++
#include <boost/python.hpp>
#include <alps/params.hpp>
#include <iostream>

// run a calculation - detached from interface (p can come from a command line)
int run(alps::params p)
{
    std::cout << p["chicken"] << std::endl;
}

// python interface
void pysolve(boost::python::dict const& parms)
{
   run(convert_to_alps_params(parms);
}

BOOST_PYTHON_MODULE(my_awesome_module)
{
     boost::python::def("solve",&pysolve);
};
```

**Comment by galexv** [comment]
ALPSCore-Python now implements unit-test capability. We do need more unit tests, but i am transplanting this issue to ALPSCore/ALPSCore-Python#5.
