### ISSUE TITLE
Overriding parameters when restarting from clone?

### ISSUE THREAD

**Issue by jgreitemann** [ALPSCore/ALPSCore#436]
Hi,
I just updated to the latest ALPSCore master and was surprised to find that it is apparently no longer supported to override parameters via command line arguments when restoring from an hdf5 archive? As far as I can tell, the relevant changes have been introduced [here](https://github.com/ALPSCore/ALPSCore/commit/b1d48f373882d084d32f31466e611aeba10facfd#diff-3276e6c2e18a491d51b5cc05704fa614R105). I always found that to be a particularly useful feature, especially when overriding the `timelimit` or parameters which are related to post-processing. Is this feature gone for good, or would it be possible to reintroduce it again? Any technical reasons that warranted removal?

**Comment by galexv** [comment]
@jgreitemann Thanks for the report, I will fix this.
