### ISSUE TITLE
Request to provide the old GF along with the new one

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#448]
Sorry Sergei @iskakoff, but that was a premature move.

When I approved #408 back in December I saw both versions of GF (old and new) in the source code. So I thought the old GF would be deemed deprecated and kept in the sources for some time. Now I realize that the old GF was completely removed by 0344cfdb3d6b82dcf7bee5cf08682fc451d5b8ae, days after my approval.

There are three branches being actively developed in the inchworm repository at the moment. Now  we are instantly forced to put our current tasks aside and to get into a rebasing mess caused by
urgent porting of the Keldysh GF container, which is inherited from ALPSCore GF. Moreover, such porting requires some changes to the library (#447 and more to come) that will need to be approved.

Most of this pain would be spared if we could simply change our includes from `<alps/gf/gf.hpp>` to something like`<alps/gf/deprecated/gf.hpp>` for the time being. Then do proper porting in a week or two...

Besides, such a profound breaking change asks for a version bump. How can CMake scripts in my application detect that ALPSCore GF is a completely different thing now?

**Comment by galexv** [comment]
Hmm, i thought it is interface-compatible...

> Most of this pain would be spared if we could simply change our includes from <alps/gf/gf.hpp> to something like<alps/gf/deprecated/gf.hpp> for the time being. 

This is probably not so hard to bring back (Sergey @iskakoff, am i correct?) 
But wouldn't it be possible just pull the commit right before the merge and use it for inchworm development, for the time being?

> Besides, such a profound breaking change asks for a version bump. How can CMake scripts in my application detect that ALPSCore GF is a completely different thing now?

This is a good point. This policy is not yet set up properly (something to discuss during the meeting).
Probably we should increase the minor version in the master branch immediately after release, so that it is possible to refer at least to the "last released version".

**Comment by galexv** [comment]
I suggest changing the issue title to something like "Request to provide the old GF along with the new one".

**Comment by krivenko** [comment]
> Hmm, i thought it is interface-compatible...

Not quite.
Well, the internal storage type is different, which means that at least `data()` method is affected.
There are also some issues to be fixed in the new GF.

> But wouldn't it be possible just pull the commit right before the merge and use it for inchworm development, for the time being?

For this very purpose I already pushed a tag named `last_old_gf`.
But this is a mess again, because now I have to maintain two ALSPCore installations.

Anyhow, my main point here is that removing features without first deprecating them is very annoying and may affect lots of potential library users.

**Comment by krivenko** [comment]
> Probably we should increase the minor version in the master branch immediately after release, so that it is possible to refer at least to the "last released version".

Now I realize that sticking to a fixed release of ALPSCore makes more sense than trying to follow `master`...

**Comment by krivenko** [comment]
I am done with porting.
If you feel like re-adding the old gf, go ahead and reopen this issue.
