### ISSUE TITLE
Cannot determine compiler features when building on Flux with Intel.

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#452]
```sh
$ module add cmake/3.5.2  boost/1.64.0 intel/17.0.1 hdf5/1.8.16/intel/17.0.1
$ CC=$(which icc) CXX=$(which icpc) \
   cmake /path/to/ALPSCore_src \
   -DCMAKE_INSTALL_PREFIX=$PWD/install \
   -DCMAKE_BUILD_TYPE=Debug \
   -DALPS_INSTALL_EIGEN=true \
   -DALPS_EIGEN_TGZ_FILE=$PWD/3.3.4.tar.gz
   -DENABLE_MPI=false 
```
Error: 
> target_compile_features no known features for CXX compiler
  "Intel"
   version 17.0.1.20161005.

The same error is there for Intel 14.

**Comment by galexv** [comment]
For the record: use of ["metafeatures"](https://cmake.org/cmake/help/v3.8/manual/cmake-compile-features.7.html#requiring-language-standards) may help here, but they are available only starting with CMake 3.8.

**Comment by iskakoff** [comment]
the same issue on Cori

**Comment by galexv** [comment]
@iskakoff Quick workaround is described at https://github.com/ALPSCore/ALPSCore/issues/313#issuecomment-364187513 (but i am working on a fix).

**Comment by iskakoff** [comment]
@galexv I just revert to the commit where this issue does not exist.

**Comment by galexv** [comment]
Just checked: a reasonably recent CMake understands reasonably recent Intel compilers. E.g., [Cmake 3.11.1](https://cmake.org/cmake/help/v3.11/release/3.11.html) understands Intel 18.0.1.
