### ISSUE TITLE
error in template? load std::vector<double>

### ISSUE THREAD

**Issue by jpfleblanc** [ALPSCore/ALPSCore#467]
When compiling our inverter code (https://github.com/CQMP/inverter ) with updated alpscore, receive error:

`[ 13%] Building CXX object CMakeFiles/inverter.dir/mc_vertex.cpp.o
In file included from /home/jpfleblanc/alps_core/ALPSCore_updated/install/include/alps/params.hpp:11:0,
                 from /home/jpfleblanc/alps_core/update/inverter/vertexaux.h:17,
                 from /home/jpfleblanc/alps_core/update/inverter/mc_vertex.h:3,
                 from /home/jpfleblanc/alps_core/update/inverter/mc_vertex.cpp:1:
/home/jpfleblanc/alps_core/ALPSCore_updated/install/include/alps/hdf5/archive.hpp: In instantiation of ‘void alps::hdf5::load(alps::hdf5::archive&, const string&, T&, std::vector<long unsigned int>, std::vector<long unsigned int>) [with T = std::vector<double>; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/jpfleblanc/alps_core/ALPSCore_updated/install/include/alps/hdf5/archive.hpp:423:17:   required from ‘alps::hdf5::archive& alps::hdf5::operator>>(alps::hdf5::archive&, alps::hdf5::detail::make_pvp_proxy<T>) [with T = std::vector<double>&]’
/home/jpfleblanc/alps_core/update/inverter/mc_vertex.cpp:83:93:   required from here
/home/jpfleblanc/alps_core/ALPSCore_updated/install/include/alps/hdf5/archive.hpp:339:13: error: ‘class std::vector<double>’ has no member named ‘load’
             value.load(ar);
             ^
`
can someone check that this is reproducible?

**Comment by galexv** [comment]
James (@jpfleblanc), could you please try to add `#include <alps/hdf5/vector.hpp>`  somewhere at https://github.com/CQMP/inverter/blob/master/mc_vertex.cpp#L4 and see if the error goes away?

**Comment by egull** [comment]
@jpfleblanc any update?

**Comment by egull** [comment]
I will close this – no response. Please feel free to reopen if the problem is still there.
