### ISSUE TITLE
[ALEA] How to multiply a result by a constant?

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#469]
I want to compute a linear transformation of an ALEA result, which is basically a multiplication by a (complex) constant. How do I do that?

Here is a list of things I'd rather not do.

1. Have the transformation Jacobian computed using the finite-difference approximation. Because I know the answer right away.
2. Specify the finite difference step 'dx' in the constructor of `linear_prop`. See point 1.
3. Use jackknife.
4. Suffer from the runtime overhead of `std::function`.

Ideally, I'd like to be able to do this without defining my own transformer.

**Comment by mwallerb** [comment]
Ad point 1+4: this screams premature optimization to me.   can you first check that this is in fact a bottleneck? 

Ad point 3: you don't need jackknife here.

ad point 2: for a linear transform, dx does not matter.

**Comment by mwallerb** [comment]
In other words, have you checked that a simple

     alea::transform(alea::linear_prop, [](double x) -> double { return 2*x; }, my_result);

is a slowdown? This would really, really surprise me.

**Comment by krivenko** [comment]
Thank you, Markus.
I was completely overwhelmed by different overloads of `transform()` and different transformers...

> Ad point 1+4: this screams premature optimization to me. can you first check that this is in fact a bottleneck?

It is, of course, not.
It just feels weird to have to compute that Jacobian for an essentially trivial transformation.

> Ad point 3: you don't need jackknife here.

This is exactly the reason why I don't want to use it. :)

**Comment by krivenko** [comment]
I still cannot figure this out...
```c++
  transform(linear_prop(),
            [alpha](std::complex<double> x) -> std::complex<double> { return alpha*x; },
            my_result);
```
does not compile (no suitable overload).

Should I use `make_transformer(std::function<T(T)> fn)` or `linear_transformer` instead of the lambda?

Another question is about the return type of `transform()`.
`my_result` is a `batch_result<std::complex<double>>`, whereas `transform(linear_prop p, const transformer<T> &tf, const InResult &in)` returns `cov_result<T>`. Do I have to resort to the jackknife-overload of `transform()` if I want `batch_result<std::complex<double>>` as output???

**Comment by krivenko** [comment]
And there is more...

In function `template <typename T, typename InResult>
typename std::enable_if<!traits<InResult>::HAVE_COV, cov_result<T>>::type transform(linear_prop p, const transformer<T> &tf, const InResult &in)`:
```c++
if (dx == 0)
    dx = 0.125 * std::abs(in.stderror().mean());
```
Will this even compile?

**Comment by krivenko** [comment]
@mwallerb Alright, we need to meet on Monday and discuss these issues in detail. I may also have an idea on how to improve the transformation interface.

**Comment by mwallerb** [comment]
Hmm it does not? Can you open an issue then? There should be a test for this somewhere ...

I have to admit the transform part is still a little sketchy.   My favourite solution would br something like expression templates. Lets discuss on Monday

**Comment by mwallerb** [comment]
> Another question is about the return type of transform().
> `my_result` is a `batch_result<std::complex<double>>`, whereas `transform(linear_prop p, const transformer<T> &tf, const InResult &in)` returns `cov_result<T>`. Do I have to resort to the jackknife-overload of `transform()` if I want `batch_result<std::complex<double>>` as output???

Yes, because you have no guarantees that the transformation is in fact linear, `linear_prop` merely specifies that you shall, for the purpose of propagation of uncertainties, *assume* it to be linear.  This is might in fact be a bug.

> ???

Also, can you tone it down a little, please?

**Comment by krivenko** [comment]
Thank you, I received answers to all my questions.

> Also, can you tone it down a little, please? :-)

Edited my comment to make it less offensive.
