### ISSUE TITLE
Accumulator cannot be compiled without warnings

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#47]
This is a typical (harmless) warning caused by our use of ublas in clang:

In file included from /Users/egull/ALPSCore/ALPSCore/install/include/alps/accumulator/accumulator.hpp:18:
In file included from /Users/egull/ALPSCore/ALPSCore/install/include/alps/accumulator/wrappers.hpp:16:
In file included from /Users/egull/ALPSCore/ALPSCore/install/include/alps/accumulator/feature/max_num_binning.hpp:24:
In file included from /Users/egull/ALPSCore/ALPSCore/install/include/alps/numeric/outer_product.hpp:13:
In file included from /Users/egull/ALPSCore/ALPSCore/install/include/alps/type_traits/covariance_type.hpp:15:
In file included from /opt/local/include/boost/numeric/ublas/matrix.hpp:16:
In file included from /opt/local/include/boost/numeric/ublas/vector.hpp:19:
In file included from /opt/local/include/boost/numeric/ublas/storage.hpp:26:
/opt/local/include/boost/numeric/ublas/traits.hpp:45:27: warning: unused function 'boost_numeric_ublas_abs' [-Wunused-function]
  template<> unsigned int boost_numeric_ublas_abs (const unsigned int& t) {

how to get rid of it?

**Comment by galexv** [comment]
All these warnings seem to occur inside Boost headers. It is possible to tell clang to treat Boost headers as "system headers" and therefore not to issue any warnings for them: see http://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-in-system-headers As we are not Boost developers, we can treat those headers as "system".

**Comment by egull** [comment]
I agree. Let's do that, good point

**Comment by egull** [comment]
Actually there is a problem with this system header command: intel doesn't support it. So I guess we can do it on clang but not on icc.

**Comment by aeantipov** [comment]
We can disable and reenable warning "-wd" with a number. BTW, do we have -Wall by default?

**Comment by galexv** [comment]
I would better go for "system headers" approach. We do not care about warnings in Boost, but we do care about warnings in our code --- so we have to disable them selectively.

**Comment by galexv** [comment]
I think it is no problem to apply pragmas iff we are compiling with clang. 
Does intel complain about boost headers too?

**Comment by egull** [comment]
yes, it complains too. But intel complains about much more, so it may not be realistic for now to make it 'warning-less' with intel.

**Comment by galexv** [comment]
It looks like rather minor annoyance and fix may bring problems of its own. Marking as "wontfix".
