### ISSUE TITLE
[TESTS] Underscores in test names are discouraged

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#479]
According to [GTest guidlines](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-should-not-test-case-names-and-test-names-contain-underscore), test cases and test names should not contain underscores (basically, because GTest itself uses underscores as delimiters). Our tests contain them in many places. It is not urgent (nothing is getting broken by it right now) but should be fixed someday. 

Please avoid underscores in the names of any new tests!

**Comment by egull** [comment]
Not important. I'm closing this because we have no plans to address it.
