### ISSUE TITLE
[ci] Eigen sometimes fails to downloaded in Travis build

### ISSUE THREAD

**Issue by mwallerb** [ALPSCore/ALPSCore#483]
This is really strange, sometimes it works, sometimes it does not.

    CMake Error at common/cmake/ALPSEnableEigen.cmake:85 (message):
      Failed to download
      /home/travis/build/ALPSCore/ALPSCore/build/eigen/eigen.tgz from
      http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz: status=22"HTTP response
      code said error"
    Call Stack (most recent call first):
      utilities/CMakeLists.txt:38 (add_eigen)

Maybe as a workaround, let us install eigen using the package manager?

**Comment by krivenko** [comment]
It looks much like Travis CI is experiencing network connectivity problems...
Here is another, seemingly related problem: https://github.com/travis-ci/travis-ci/issues/9112

**Comment by galexv** [comment]
Yes, i think so. Closing.
