### ISSUE TITLE
[ALEA] Return types of count() and count2() are different between *_data and *_result classes

### ISSUE THREAD

**Issue by krivenko** [ALPSCore/ALPSCore#484]
Return types of count() and count2() methods are inconsistent (`size_t` vs `double`) between result classes and their respective data classes. Out of 5 pairs of classes, only `mean_result`/`mean_data` aren't affected by this problem, I guess.

**Comment by krivenko** [comment]
Wait a minute, `count2()` still has inconsistent return types...
```
(13:00) igor@floquet ~/Physics/ALPSCore/ALPSCore.git/alea/include/alps/alea [pr507] $ grep -R "count2() const" *
batch.hpp:    double count2() const { return store_->count().squaredNorm(); }
covariance.hpp:    double count2() const { return count2_; }
covariance.hpp:    size_t count2() const { return store_->count2(); }
variance.hpp:    double count2() const { return count2_; }
variance.hpp:    size_t count2() const { return store_->count2(); }
```

**Comment by mwallerb** [comment]
Yes, but this needs to be that way, because `size2_` is potentially `size_ * size_`

**Comment by mwallerb** [comment]
Ah no, shit, you're right ...
