### ISSUE TITLE
warning on "unsupported tag"

### ISSUE THREAD

**Issue by ahaichen** [ALPSCore/ALPSCore#489]
a series warning on some "unsupported tag" are generated when Make the current version ALPSCore. It seems they do not influence the code. Just post here as a note.  

Warning: ignoring unsupported tag `ALLOW_UNICODE_NAMES    =' at line 79, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `GROUP_NESTED_COMPOUNDS =' at line 361, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `HIDE_COMPOUND_REFERENCE=' at line 532, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `SHOW_GROUPED_MEMB_INC  =' at line 545, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `WARN_AS_ERROR          =' at line 756, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `LATEX_EXTRA_STYLESHEET =' at line 1742, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `LATEX_TIMESTAMP        =' at line 1809, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `RTF_SOURCE_CODE        =' at line 1875, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `MAN_SUBDIR             =' at line 1910, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `DOCBOOK_PROGRAMLISTING =' at line 1973, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `DIA_PATH               =' at line 2184, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `DIAFILE_DIRS           =' at line 2398, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `PLANTUML_JAR_PATH      =' at line 2406, file /home/alanchen/download/ALPSCore/build/Doxyfile
Warning: ignoring unsupported tag `PLANTUML_INCLUDE_PATH  =' at line 2411, file /home/alanchen/download/ALPSCore/build/Doxyfile

**Comment by galexv** [comment]
It looks like a Doxygen problem. What does "doxygen --version" say?

**Comment by ahaichen** [comment]
1.8.5

**Comment by galexv** [comment]
The warnings are harmless, i will see what is the easiest way to remove them (i guess, it's trimming down the Doxyfile to a bare minimum: the less directives there are, the less unknown directives there will be).

**Comment by egull** [comment]
Thanks for reporting. The reason here is that the doxygen version (1.8.5) is older than the doxygen file version (Doxyfile 1.8.11). Doxygen will still work, it just gives these warnings. For now I'd ignore this - it's not worth trimming the file down by hand.

I'll close this for now.
