### ISSUE TITLE
input parameters with -- in command line still supported?

### ISSUE THREAD

**Issue by dombrno** [ALPSCore/ALPSCore#493]
Godd afternoon, 
I have developed a code  which uses the ALPSCore libraries, and unfortunately I have not had the courage/energy/wisdom to keep up with the updates of ALPSCore as they were coming. This means that my code has been using the tag 156ce1e9bb1b1fc39e69f7e7359722d498185df6 ever since it was created (5/12/2016 :( ). Recently, I have needed to used ALPSCORE/CT-HYB in one of its more recent versions, and have thus upgraded the whole framework ALPSCORE/CT-HYB  and ALPSCORE/ALPSCore. After some modification of the params handling, compilation went fine, but now I realize that my using the -- option to specify the values of parameters in the command line, instead of in the *.ini file fails completely, with the error message "HDF5 arhive must be the only argument".

Thus, I am wondering if passing parameters via the command line and -- is still supported, and I am doing something wrong, or if it has been removed?

My code is at https://github.com/dombrno/SC_Loop_ALPSCore if you wish to look at it, and the handling of the parameters is done in the first few lines of the main, and in  void define_parameters(alps::params &parameters) in main.cpp.

Thanks a lot!

**Comment by galexv** [comment]
Overriding parameters supplied via HDF5 file in command line is not yet supported (it is issue #436). This is planned to be fixed soon.
Supplying parameters via the command line uses `--name=value` syntax (with dashes optional) or `--option` for boolean options (`--option` is a shortcut for `--option=true`, which is in turn equivalent to `option=true`).
An argument that contains neither leading `-` nor `=` is interpreted as a file name to be read and parsed.
If both INI files and command-line options are supplied, INI files are parsed first, followed by the command-line options; the command-line options override the settings from the INI files.

**Comment by dombrno** [comment]
Thank you for this. I only use parameters supplied via INI file, and override some in command line.

Using the syntax which you just indicated, this seems to be working fine in the current version, so I think we can close this issue?

Thanks a lot for your work, and for the amazing support.
