### ISSUE TITLE
Compilation failure with Boost 1.58 and C++14

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#497]
As reported by Hiroshi (@shinaoka), the compilation of ALPSCore in C++14 mode with Boost 1.58 fails (see issue https://github.com/ALPSCore/ALPSCore/issues/465#issuecomment-378250432 and https://svn.boost.org/trac10/ticket/11251). 
The workaround for now is to use a newer version of Boost.

**Comment by shinaoka** [comment]
It may be better to check C++14 build in Travis CI as follows.
https://github.com/shinaoka/ALPSCore/blob/master/.travis.yml

What do you think?
A drawback is that we need to use gcc 5 for C++14.

**Comment by galexv** [comment]
Moved CI discussion to issue #498.

**Comment by shinaoka** [comment]
Is it easy to workaround the bug in Boost 1.58 by modifying ALPSCore?
If not, we should put this into the trouble shooting on wiki.

**Comment by galexv** [comment]
Closed by commit dc3b2d9 (PR #499).
