### ISSUE TITLE
Allow compilation with C++17

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#500]
As suggested in https://github.com/ALPSCore/ALPSCore/issues/498#issuecomment-378413474, enable C++17 support by CMake script. 
See also #452: we may require sufficiently new CMake.

**Comment by galexv** [comment]
@egull Shall we bump the required CMake version to 3.8? It may also help with #452.
[Precompiled cmake binaries](https://cmake.org/files/v3.8/) are readily available for Linux and MacOS, so they can be installed by users even a particular system does not have them by default. The only concern is exotic systems like Cray; i have checked that, e.g., on NERSC Cori cmake 3.8.2 is available.

**Comment by egull** [comment]
I'm ok with a one year old version... Can we get away with that?

**Comment by shinaoka** [comment]
The ISSP supercomputer has cmake 3.2.3, but it should be upgraded easily.
