### ISSUE TITLE
Eigen::tensor?

### ISSUE THREAD

**Issue by dombrno** [ALPSCore/ALPSCore#501]
Good morning,

This is not an issue report, but only a suggestion for the (far) future. At the moment, at the level of the interface between h5 storage and client codes, it seems like the usual practice is to read/write data to/from hdf5 from/into boost::multiarray objects, which ALPSCORE supports very well.

Unfortunately, the boost::multiarray library is really only about containers, and as soon as one wishes to do any operation on the data, as simple as adding two multiarrays, nothing is available from boost. The library itself seems to not be under development anymore, so that it will remain a "container only" library for the foreseeable future. As a consequence, if the data needs to be used for more advanced treatment, after being read from h5 into multiarray, it needs to be transferred to an ad hoc container first, following h5 -> multiarray -> ad hoc container -> computation -> multiarray -> h5.

In the past, I have been using Eigen::Matrix objects, with great satisfaction, but they are limited to 1D or 2D data. Recently, I have discovered that the [Eigen::tensor](http://eigen.tuxfamily.org/index.php?title=Tensor_support) is being developed. It is still in beta but looks very promising. I am now using and it is very convenient, so I just wanted it to point out the existence of the lib to the team.

**Comment by egull** [comment]
We are aware of Eigen Tensor and use it in some of our codes. At the moment it is not supported in Eigen's the default release. Once it will be released (and the released version widely adopted), we will make ALPS aware of it.

**Comment by dombrno** [comment]
Thank you.
