### ISSUE TITLE
Permission issue in parsing an ini file

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#502]
Hi, I got some feedback from an user of the new ALPSCore/CT-INT code.
There is some problem in the ALPSCore parameter libraries.

I've reproduced the same problem on Mac.
I installed the binary of the  CT-INT into a system directory "/opt/ctint/bin".
Then, I invoked the problem as

```
/opt/ctint/bin/ctint_real input.ini
```

The input file is parsed by the parameter libraries as
https://github.com/ALPSCore/CT-INT/blob/master/src/main.hpp#L16

But , I got the runtime error

```
std::runtime_error: Failed to generate a temporary name from template '/opt/ctint/bin/ctint_real.param.inic2rFd4'
```

Clearly, the parameter libraries failed to create a temporary file in the system directory, where I do not have a write permission.
I tracked down the cause of this problem to 
https://github.com/ALPSCore/ALPSCore/blob/master/params/src/params.cpp#L233

I think it is not a good idea to create a temporary file in the directory where our binary is.
What is the idea behind this implementation?
It may be better to create a temporary file in the working directory where our ini file exists.

**Comment by galexv** [comment]
The temporary file is not a good approach to begin with (it's a limitation of the chosen INI library), and have it based on the _full path_ of the executable is likely a mistake. I'll fix this.

**Comment by shinaoka** [comment]
Thank you for the reply.
How long does it take to fix this?

**Comment by egull** [comment]
@galexv, let's look at this when you come in. Do you have time 9-9:30? We should get it done then...

**Comment by shinaoka** [comment]
Thank you! Looking forward to see some solution from you...

**Comment by galexv** [comment]
I will fix it in an hour, i think.

**Comment by galexv** [comment]
@shinaoka I have merged the fix to the master branch.

**Comment by shinaoka** [comment]
Thank you. I've confirmed that the fix works on my laptop!
Let us close the issue!
