### ISSUE TITLE
[accumulators] test `repeated_merge` fails when run in parallel

### ISSUE THREAD

**Issue by mwallerb** [ALPSCore/ALPSCore#508]
On the old accumulator framework, when running:

    $ mpirun -np 2 ./accumulators/test/repeated_merge

I get:

    /home/mwallerb/Workspace/alpscore/accumulators/test/repeated_merge.cpp:91: Failure
    Value of: rset["value"].count()
      Actual: 50000
    Expected: rset["test_value"].count()
    Which is: 40000
    Count
    [  FAILED  ] AccumulatorTest/1.twoMerges, where 
      TypeParam = (anonymous namespace)::proxy<alps::accumulators::NoBinningAccumulator, double> (20 ms)

It fails for all other accumulator types as well.

NB: I think we should run the tests in parallel on travis as well to check for that sort of thing.

**Comment by galexv** [comment]
Looking at it...

**Comment by galexv** [comment]
Commit c987a08cf5b18d54149e164aecbb0d9feed67bec is last good (aka PR #380), commit 97d4b696ca4ec0ace8090fbf7aa4b7f9837ca0d1 is first bad: merging the master into the feature branch (issue #295).
