### ISSUE TITLE
[travis] run tests in parallel to check for MPI issues

### ISSUE THREAD

**Issue by mwallerb** [ALPSCore/ALPSCore#511]
Given bugs #508 and #509, I think we should run tests in parallel on travis.

Something like

    $ ALPS_TEST_MPI_NPROC=4 make test

here: https://github.com/ALPSCore/ALPSCore/blob/master/.travis.yml#L59

**Comment by galexv** [comment]
Closed by commit c1c69da06137b7c01f1f73379fec03d092ff8f0c.
