### ISSUE TITLE
Set up MacPorts testing on TravisCI

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#536]
TravisCI uses homebrew. OTOH, it would be good to test our Port before submitting it to Macports repo (especially considering that not all devs here have Macs). Good starting point is, e.g., https://github.com/GiovanniBussi/macports-ci/blob/master/macports-ci .

**Comment by egull** [comment]
I can test the updated Port file and submit it to macports, no problem.

**Comment by galexv** [comment]
Fixed by ALPSCore/packaging@9b5c3a9818329fbfdefdb9badb806a3bc0ded30d.
