### ISSUE TITLE
Example CMakeLists.txt

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#54]
Write an example CMake file for a typical external project to show how the library should be used. @aeantipov has one but it doesn't work with cmake 3.0, @jpfleblanc needs one...

**Comment by egull** [comment]
Hm, so what we should have is something like this:

cmake_minimum_required(VERSION 3.0)
list(APPEND CMAKE_MODULE_PATH /Users/egull/ALPSCore/ALPSCore/install/share/cmake/Modules/)
project (mc_example)

find_package(hdf5 REQUIRED)
find_package(ALPSCore REQUIRED COMPONENTS hdf5 accumulators mc params)

find_package (Boost COMPONENTS program_options filesystem system serialization REQUIRED)

include_directories(${Boost_INCLUDE_DIRS})
include_directories(${ALPSCore_INCLUDES})



add_executable(mc_example mc_example.cpp)

target_link_libraries(mc_example
${ALPSCore_LIBRARIES}
${Boost_LIBRARIES}
)

...followed by instructions to 1. have the environment variable CMAKE_PREFIX_PATH set:
CMAKE_PREFIX_PATH=/Users/egull/ALPSCore/ALPSCore/install/share/cmake/Modules/
...and 2. to have it run with ALPS_ROOT set:
cmake -DALPS_ROOT=/Users/egull/ALPSCore/ALPSCore/install/ .

that seems to do the trick, but it should find its way into a tutorial.

**Comment by egull** [comment]
quick comment after looking over this: why does ALPS_ROOT not get set by the find_package ALPS scripts?

**Comment by aeantipov** [comment]
I think it does immediately after the first package is found. But if no package is found, then ALPS_ROOT won't be set.

**Comment by egull** [comment]
No, there must be a bug then: if you just use the find_package command, ALPS_ROOT is not set and has to be specified by hand.

**Comment by egull** [comment]
to be done with rest of tutorials.

**Comment by egull** [comment]
I believe the updated version is now:

cmake_minimum_required(VERSION 3.0)

project (mc_example)

find_package(hdf5 REQUIRED)
find_package(ALPSCore REQUIRED COMPONENTS hdf5 accumulators mc params)

find_package (Boost COMPONENTS program_options filesystem system serialization REQUIRED)

include_directories(${Boost_INCLUDE_DIRS})

add_executable(mc_example mc_example.cpp)

target_link_libraries(mc_example
${ALPSCore_LIBRARIES}
${Boost_LIBRARIES}
)

and all the other tricks are no longer necessary, unless the ALPS_ROOT is something non-standard, in which case one should do:
 cmake -DALPS_ROOT=/Users/egull/ALPSCore/ALPSCore/install/ .
...otherwise just cmake .

**Comment by galexv** [comment]
Actually, if the location is non-standard, use:

     env ALPSCore_DIR=/Users/egull/ALPSCore/ALPSCore/install/ cmake .
     
(it is the CMake-standard way to point to location of `*Config.cmake` files.)

If the user wants to use `ALPS_ROOT`, he/she should use something like

    find_package(ALPSCore REQUIRED COMPONENTS hdf5 accumulators mc params HINTS ${ALPS_ROOT})

or maybe 

    find_package(ALPSCore REQUIRED COMPONENTS hdf5 accumulators mc params PATHS ${ALPS_ROOT} NO_DEFAULT_PATH)

in `CMakeLists.txt`.

**Comment by egull** [comment]
I guess we can simplify the CMakeLists.txt once we have the fix of #125 but for now I close this.
