### ISSUE TITLE
Test: nonexistent failed with intel c++ in Debug build 

### ISSUE THREAD

**Issue by iskakoff** [ALPSCore/ALPSCore#541]
```
accumulator.nonexistent_acc
Assertion failed: (px != 0), function operator->, file ...boost/smart_ptr/shared_ptr.hpp, line 648.
<end of output>
```

Probably fixed by #538

**Comment by egull** [comment]
Can you have a quick look if #538 actually fixes it, and if so we'll merge right away.

**Comment by iskakoff** [comment]
I have icc (ICC) 16.0.4 20160811
and the error is still there

**Comment by galexv** [comment]
Cf #75 ?

**Comment by galexv** [comment]
Cannot reproduce it with Intel 16.0.3 20160415 on flux. The error seems awfully specific to the compiler version. Shall we close it till we get more reports?

**Comment by egull** [comment]
Yeah. I think this is something wrong with Intel and we should just ignore it until it comes back in some other way.
