### ISSUE TITLE
[packaging] Build failures on some Mac OSX boxes

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#553]
This issue is to track problems in packaging repo:

- [ ] ALPSCore/packaging#9 
- [x] ALPSCore/packaging#10 
- [x] ALPSCore/packaging#11

**Comment by galexv** [comment]
All seems to be corrected by the proper blacklisting, except this one:
https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/70669

Which is issue #576.

**Comment by egull** [comment]
All seems to be correct now.
