### ISSUE TITLE
[alea] Add tutorial

### ISSUE THREAD

**Issue by mwallerb** [ALPSCore/ALPSCore#574]
Complaint by @krivenko , who considers it a blocker for the paper.

**Comment by krivenko** [comment]
Well, if this is too much of a pain to do, I'd rather change the wording in the abstract.
The GF tutorial is also missing so writing all this stuff could take ages.

**Comment by egull** [comment]
I disagree. It's a good idea to have those new features documented and explained, and it really is added value. Let's just wait for it.
