### ISSUE TITLE
[alea] copyright notice is missing

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#602]
check-module-copyright-notice.py alea finds missing copyright notices in:

alea/src/model.cpp
alea/src/testing.cpp
alea/test/model.cpp
alea/include/alps/alea/testing.hpp
alea/include/alps/alea/internal/pooling.hpp
alea/include/alps/alea/util/model.hpp

I'll prepare a pull request in the next five minutes.

**Comment by galexv** [comment]
Closed by PR #603
