### ISSUE TITLE
[website] Fix links from alpscore.org to installation instructions

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#604]
Fix "install" links from http://alpscore.org after merging PR #600  (commit 65d0db1c3f4073bce10fa5c71919850ccb7ee009).

**Comment by egull** [comment]
Also fix the citation here: 
https://raw.githubusercontent.com/ALPSCore/ALPSCore/master/ACKNOWLEDGE.TXT
by adding the newest arxiv reference.
