### ISSUE TITLE
Merging two accumulators

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#61]
When I do staging, I have old and new data - each being an alps::accumulator. What is the right way of merging the two?

**Comment by galexv** [comment]
As of commit 3824d7b implemented for everything except FullBinningAccumulators.
I am moving this to a next release.

**Comment by galexv** [comment]
Implementation for FullBinning needs proper testing, see issue #172.

**Comment by egull** [comment]
@mwallerb can this be closed because Alea has corresponding functionality that works?

**Comment by mwallerb** [comment]
No, not yet. "Merging" accumulators is IMHO a little bit of a misnomer, since it means adding the accumulated values of one accumulator to another.  After discussion with @kleinhenz and @krivenko, who need this, I'm working on implementing the following:

    mean_acc<T> &mean_acc<T>::operator<<(const mean_result<T> &);
