### ISSUE TITLE
[documentation] Describe compilation failure in low-memory environments

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#610]
It is very possible to see ALPSCore fail to compile, usually somewhere in legacy accumulators, when there is not enough memory available for the compiler. The message is something like this (highlighted for clarity):
```diff
 Scanning dependencies of target alps-accumulators
 [ 27%] Building CXX object accumulators/CMakeFiles/alps-accumulators.dir/src/wrapper_set_hdf5.cpp.o
-g++: fatal error: Killed signal terminated program cc1plus
-compilation terminated.
 make[2]: *** [accumulators/CMakeFiles/alps-accumulators.dir/src/wrapper_set_hdf5.cpp.o] Error 1
 make[1]: *** [accumulators/CMakeFiles/alps-accumulators.dir/all] Error 2
 make: *** [all] Error 2
```
The remedy is to make sufficient memory available to C++ (at least 2GB).

This behavior should be documented.

**Comment by iskakoff** [comment]
sometimes even 2Gb is not enough. I had problem with some version of Intel 2016, in -O3 it ate about 20Gb and crashed.

**Comment by galexv** [comment]
Added a notice to the wiki:
https://github.com/ALPSCore/ALPSCore/wiki/Known-problems-and-workarounds#build-fails-when-compiling-legacy-accumulators-with-a-message-killed-or-terminated
