### ISSUE TITLE
Jenkins OSX build fails with MPI and Python

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#73]
Continuation of issue #66: Boost missing `boost_mpi`, `boost_python` modules.
Switched off MPI and Python features on Jenkins OSX builds as a temporary measure.

**Comment by egull** [comment]
For a user on macports this probably would mean using boost with variants
   openmpi: Build using the OpenMPI compiler
     * conflicts with mpich mpich_devel openmpi_devel
(+)python27: Build Boost.Python for Python 2.7
     * conflicts with debug python25 python26 python31 python32 python33 python34
...or similar.

For jenkins we should precompile boost. For howto see macports variants file, get inspired from /opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/devel/boost/Portfile

**Comment by egull** [comment]
I think we can resolve this one by using the boost python provided by homebrew, and testing mpi and python on the homebrew version. Needs fixing of #105

**Comment by aeantipov** [comment]
There is a small problem - boost is precompiled w homebrew only with default flags, i.e. without python and, more important, mpi. It is possible to have a precompiled version of boost be deployed with homebrew, but it requires some preparations. See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md

**Comment by egull** [comment]
to come back to this: we can run an external build on Xi's machine with mpi and python the same way we do it for icc. Requires fixing #78

**Comment by egull** [comment]
Did that, and that build (called alpscore_osx_mpi) exists, builds, and passes all tests.
