### ISSUE TITLE
Issue when inverting observables

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#77]
We have a SERIOUS bug when inverting an observable, i.e. dividing a scalar by an observable. I've added a test, invert_accumulators, that shows the issue: essentially, 1./0.5 should be 2 but is 0.5.

..this is an accumulator bug that seems to have been there before (!)

**Comment by galexv** [comment]
It seems that `res1.operator/ (res2)` is defined via `operator/=`, roughly as  `{ res1_clone=res1; res1_clone /= res2; return res1_clone; }`, and it works. On the other hand, `operator/(double x, res1)` is defined roughly as `{ return x*res1.inverse()}`, and it is `res1.inverse()` that does not work. The definition of the `inverse()` operation boils down to implementing it for each accumulator feature (mean, error, _etc_.)--- and those implementations seem to be missing! (?)  Looking at it now...

**Comment by galexv** [comment]
The implementations of inverse() seems to be in place and working. The inverted value is getting lost on the way up to the caller, somehow. One suspicious place (accumulators.hpp, line 345) is fixed, still no luck. :(  Working on it... :)

**Comment by galexv** [comment]
The unary minus operator is implemented in a similar way, by calling `negate()` method --- and it does not seem to work either.

**Comment by galexv** [comment]
Seems to be fixed by commit 57be037.

**Comment by egull** [comment]
OK, this is fixed. Issue #80 though did not get fixed by it, let's have a look at it tomorrow.
