### ISSUE TITLE
A vector observable cannot be divided by a scalar observable in accumulator

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#79]
A typical scenario is this: we measure a vector observable and divide it by a scalar sign. this is currently not supported, ALPS throws an exception:

C++ exception with description "only results with equal value types are allowed in operators

It should be possible to divide a vector observable by a scalar observable.

**Comment by egull** [comment]
Alex, could you please have a look at this one tomorrow? It stops an application from being ported...

**Comment by galexv** [comment]
Yes, sure.

**Comment by galexv** [comment]
Commit 66ba01b should fix it. Proper testing pending. I also see a couple of warnings by clang. 
@egull: Emanuel, could you please have a look whether it works as expected in your code?

**Comment by galexv** [comment]
Seems like all icpc tests fail. :( I will look at it. ;)

**Comment by galexv** [comment]
The failure is because Boost libraries cannot find MPI libraries anymore:

```ShellSession
cqmp1:test jenkins-user$ ./count
dyld: Library not loaded: /opt/local/lib/openmpi-mp/libmpi.1.dylib
  Referenced from: /opt/local/lib/libboost_filesystem-mt.dylib
  Reason: image not found
```
That's why people use containers like Docker. :)

**Comment by galexv** [comment]
Seems to be working --- closing.
