### ISSUE TITLE
Division of vector results results in vecor of size zero

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#80]
as illustrated in the test divide_accumulators that references this issue.

**Comment by egull** [comment]
had a closer look at this and ended up at the place you were working at earlier, so I think this is related to issue #77

**Comment by galexv** [comment]
There is nothing special about division :), multiplication `res1*res2` exhibits the same bug, as well as addition `res1+res1`.  :(  `Result<...>::generate_jackknife()` method is the primary suspect.

**Comment by galexv** [comment]
The issue is fixed by commit 5de13ce, closing it...
