### ISSUE TITLE
cmake find module for alpscore-python

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#81]
We don't have one yet.

**Comment by egull** [comment]
Andrey, you wrote the previous ones, right? How easy is it to just duplicate them and make them work for python?

**Comment by aeantipov** [comment]
Sure. I will do that now then )On Sun, Jan 18, 2015 at 10:36,  ALPSCore/ALPSCore <reply@reply.github.com> wrote:            Andrey, you wrote the previous ones, right? How easy is it to just duplicate them and make them work for python?

**Comment by aeantipov** [comment]
Fixed with https://github.com/ALPSCore/ALPSCore/commit/e6962cd9a7993a566d24aafa82a9620a6317582b
