### ISSUE TITLE
Verbosity level for accumulators

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#83]
It would be handy to specify verbosity level for accumulators, i.e. now I have smth like
<pre>
==========================
Results (no normalization)
==========================
dm0: 0.419913 #200889 +/-0.00781443 Tau: 24.6806
    bin #  1 entries: error = 0.00110116
    bin #  2 entries: error = 0.00153156
    bin #  3 entries: error = 0.00211917
    bin #  4 entries: error = 0.00289585
    bin #  5 entries: error = 0.00387497
    bin #  6 entries: error = 0.00501342
    bin #  7 entries: error = 0.0061893
    bin #  8 entries: error = 0.00725584
    bin #  9 entries: error = 0.00781443
 Bins: [0.519531,..128..,0.301432]#512
dm1: 0.28348 #200889 +/-0.0089483 Tau: 39.0963
    bin #  1 entries: error = 0.00100554
    bin #  2 entries: error = 0.00140586
    bin #  3 entries: error = 0.00195794
    bin #  4 entries: error = 0.00269997
    bin #  5 entries: error = 0.00367562
    bin #  6 entries: error = 0.00489533
    bin #  7 entries: error = 0.00627598
    bin #  8 entries: error = 0.0077338
    bin #  9 entries: error = 0.0089483
 Bins: [0.195964,..128..,0.261719]#512
dm2: 0.274988 #200889 +/-0.00898638 Tau: 40.1851
    bin #  1 entries: error = 0.000996213
    bin #  2 entries: error = 0.00139225
    bin #  3 entries: error = 0.00193874
    bin #  4 entries: error = 0.00267783
    bin #  5 entries: error = 0.00364017
    bin #  6 entries: error = 0.00483418
    bin #  7 entries: error = 0.00622945
    bin #  8 entries: error = 0.00775289
    bin #  9 entries: error = 0.00898638
</pre>

Having something like 
`0.28348 #200889 +/-0.0089483 Tau: 39.0963 [9]` would be my primary choice in release mode runs, while I could occassionally use full bin information from time to time.

**Comment by egull** [comment]
Consider options for release 0.6, this is not urgent right now.

**Comment by galexv** [comment]
Suggestion: `cout << acc` or `cout << result` should print a short summary (mean, error bar, autocorrelation). For the extended printing we can use a separate method, something like `full_print()`.

**Comment by galexv** [comment]
Concise printing is introduced by commit 18a8cc3. 
Verbose (debug) printing is a separate, not-so-urgent matter, so i am removing this issue from the "Accumulators" milestone --- but leaving it open.

**Comment by galexv** [comment]
The debug printing is really a separate matter. Closing as "Won't fix", can be re-opened or referenced from another issue later.

**Comment by galexv** [comment]
Closed by commit 6ff3386.
``cout << short_print(acc_set["observable"])`` and ``cout << short_print(res_set["observable"])`` can be used for short printing. For "raw accumulators", ``acc.print(cout, true)`` can be used.
