### ISSUE TITLE
Store ALPS_HAS_MPI in FindALPSCore

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#84]
ALPSCore has ENABLE_MPI flag, which enables inclusion and linking to mpi and boost::mpi libraries. When another code is linked to alpscore, that information is not stored and can not be retrieved when calling `find(ALPSCore components ...)`. This leads to linking errors, if, for example, a non-mpi code is linked to alpscore with mpi enabled.

**Comment by galexv** [comment]
Should work now. The variable is called `ALPSCore_HAS_MPI` and must be available after `find(ALPSCore)`.

**Comment by aeantipov** [comment]
Thanks!
