### ISSUE TITLE
fPIC in compiler flags

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#85]
Do you think it makes sense to add "-fPIC" to the default compilation flags when building static libraries is required? It's a typical problem, that non fPIC code can't be linked into a dynamic library, which requires having all of the dependencies static. 
On the other hand, it's a forced option, that some advanced users might like to disable. We could add it as an optional flag with default being having -fPIC. 
See http://stackoverflow.com/questions/5311515/gcc-fpic-option

**Comment by egull** [comment]
If we keep running into that problem or need it for the packages let's add it, otherwise an advanced user can specify it if they need it. Default flags is not the right place to add it, it may break on systems that don't have shared library support... we'd need to test that.

**Comment by aeantipov** [comment]
Actually, cmake devs looked into that. One good way could be to set this thing : http://www.cmake.org/cmake/help/v2.8.9/cmake.html#prop_tgt:POSITION_INDEPENDENT_CODE

**Comment by egull** [comment]
OK. I guess this goes into the master cmake file?

**Comment by egull** [comment]
first test of this on my mac shows that it works... let's test it on jenkins.

**Comment by aeantipov** [comment]
It is on by default for shared builds, so should be on for static ones.

**Comment by aeantipov** [comment]
Actually, that had to be added for every library target. Done with c033efc73480f3cbbe8bb5f9ae42aa6a5f23faa0
