### ISSUE TITLE
failing tests on intel & mpi

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#86]
OSX shows the following failing tests unter openmpi and intel c++:

phys-egull-mbp:mc egull$ make test
Running tests...
Test project /Users/egull/ALPSCore/ALPSCore/build.tmp/mc
    Start 1: sum_single
1/4 Test #1: sum_single .......................   Passed    0.05 sec
    Start 2: sum_mpi
2/4 Test #2: sum_mpi ..........................***Exception: Other  0.44 sec
    Start 3: reduce
3/4 Test #3: reduce ...........................***Exception: Other  0.38 sec
    Start 4: signed_obs
4/4 Test #4: signed_obs .......................***Exception: Other  0.36 sec

25% tests passed, 3 tests failed out of 4

Total Test time (real) =   1.23 sec

The following tests FAILED:
	  2 - sum_mpi (OTHER_FAULT)
	  3 - reduce (OTHER_FAULT)
	  4 - signed_obs (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8

....where the failures look like this:

phys-egull-mbp:mc egull$ ./test/sum_mpi
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from mc
[ RUN      ] mc.sum_mpi
e^(-x*x): 0.869115 #1 +/-inf Tau: inf
    bin #  1 entries: error = inf
 Bins: [0.869115]#1
e^(-x*x): [0.869115,..3..,0.869115] #1 +/-[] Tau: []
    bin #  1 entries: error = []
 Bins: [[0.869115,..3..,0.869115]]#1
1.86911 #1 +/-inf Tau: inf
    bin #  1 entries: error = inf
 Bins: [1.86911]#1
1.73823 #1 +/-inf Tau: inf
    bin #  1 entries: error = inf
 Bins: [1.73823]#1
Abort by signal 11

In /Users/egull/ALPSCore/ALPSCore/utilities/src/signal.cpp on 82 in segfault
[phys-egull-mbp:58139] *** Process received signal ***
[phys-egull-mbp:58139] Signal: Abort trap: 6 (6)
[phys-egull-mbp:58139] Signal code:  (0)
[phys-egull-mbp:58139] [ 0] 0   libsystem_platform.dylib            0x00007fff846fff1a _sigtramp + 26
[phys-egull-mbp:58139] [ 1] 0   ???                                 0x0000000000000009 0x0 + 9
[phys-egull-mbp:58139] [ 2] 0   libsystem_c.dylib                   0x00007fff8af77b53 abort + 129
[phys-egull-mbp:58139] [ 3] 0   libalps-utilities.dylib             0x000000010dce913d _ZN4alps6signal8segfaultEi + 1085
[phys-egull-mbp:58139] *** End of error message ***
Abort trap: 6

**Comment by egull** [comment]
...possible that this is a problem with the MPI environment.

**Comment by galexv** [comment]
Carrying over from issue #95. I see that `accumulators/include/alps/accumulators/mpi.hpp` uses

     std::size_t size = std::accumulate(extent.begin(), extent.end(), 0);

in multiple places. However, at least at one location, to work correctly (see #95), it had to be replaced by

     size=std::accumulate(extent.begin(), extent.end(), 1, std::multiplies<std::size_t>())

which makes more sense (multiplying the extents of an array to calculate its size, rather than summing them, which would give &mdash; what? perimeter?).

It certainly looks suspicious. I will have a second look at it now. Possibly, address sanitizer (our #35) can help here.

**Comment by galexv** [comment]
Emanuel, if/when you have time, can you check whether b513b8b fixed this too?

**Comment by egull** [comment]
no, it did not fix it, but now crashes differently (presumably during a cleanup?)

0587388619:mc egull$ ./test/sum_mpi
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from mc
[ RUN      ] mc.sum_mpi
1+x: 1.50005 #797568 +/-0.000297789 Tau: -0.0757824
    bin #  1 entries: error = 0.000323295
    bin #  2 entries: error = 0.000323244
    bin #  3 entries: error = 0.000322577
    bin #  4 entries: error = 0.000323092
    bin #  5 entries: error = 0.000323778
    bin #  6 entries: error = 0.000324359
    bin #  7 entries: error = 0.000323428
    bin #  8 entries: error = 0.000324758
    bin #  9 entries: error = 0.000321227
    bin # 10 entries: error = 0.000317286
    bin # 11 entries: error = 0.000310866
    bin # 12 entries: error = 0.000300405
    bin # 13 entries: error = 0.000297789
 Bins: [1.5001,..97..,1.49602]#8192
1+x: [1.50005,..3..,1.50005] #797568 +/-[0.000297789,..3..,0.000297789] Tau: [-0.0757824,..3..,-0.0757824]
    bin #  1 entries: error = [0.000323295,..3..,0.000323295]
    bin #  2 entries: error = [0.000323244,..3..,0.000323244]
    bin #  3 entries: error = [0.000322577,..3..,0.000322577]
    bin #  4 entries: error = [0.000323092,..3..,0.000323092]
    bin #  5 entries: error = [0.000323778,..3..,0.000323778]
    bin #  6 entries: error = [0.000324359,..3..,0.000324359]
    bin #  7 entries: error = [0.000323428,..3..,0.000323428]
    bin #  8 entries: error = [0.000324758,..3..,0.000324758]
    bin #  9 entries: error = [0.000321227,..3..,0.000321227]
    bin # 10 entries: error = [0.000317286,..3..,0.000317286]
    bin # 11 entries: error = [0.000310866,..3..,0.000310866]
    bin # 12 entries: error = [0.000300405,..3..,0.000300405]
    bin # 13 entries: error = [0.000297789,..3..,0.000297789]
 Bins: [[1.5001,..3..,1.5001],..97..,[1.49602,..3..,1.49602]]#8192
[       OK ] mc.sum_mpi (1019 ms)
[----------] 1 test from mc (1019 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1019 ms total)
[  PASSED  ] 1 test.
Abort by signal 11

In /Users/egull/ALPSCore/ALPSCore/utilities/src/signal.cpp on 82 in segfault
[0587388619:66794] *** Process received signal ***
[0587388619:66794] Signal: Abort trap: 6 (6)
[0587388619:66794] Signal code:  (0)
[0587388619:66794] [ 0] 0   libsystem_platform.dylib            0x00007fff8ad08f1a _sigtramp + 26
[0587388619:66794] [ 1] 0   ???                                 0x0000000000000009 0x0 + 9
[0587388619:66794] [ 2] 0   libsystem_c.dylib                   0x00007fff8cc93b53 abort + 129
[0587388619:66794] [ 3] 0   libalps-utilities.dylib             0x00000001074cb29d _ZN4alps6signal8segfaultEi + 1085
[0587388619:66794] *** End of error message ***
Abort trap: 6
0587388619:mc egull$

**Comment by galexv** [comment]
> but now crashes differently (presumably during a cleanup?)

maybe, during `MPI_Finalize()`?.. I guess i have to log in to your computer and have a look. :-)

I will try to reproduce it on another MAC, with icc and OpenMPI.

**Comment by egull** [comment]
Could also be my MPI installation locally.

**Comment by egull** [comment]
Let's close this as 'invalid' for now. If we see it on other installations we'll need to investigate, I suspect that it has something to do with the MPI installation, not with ALPS.
