### ISSUE TITLE
put scope and goals on the front page

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#88]
subj - we should put a text on the front page, that tells 
- what is that alpscore does
- how is it different from alps 
- how does it interface with other libraries and what are the dependencies. 
- point to examples/tutorials using alpscore

**Comment by egull** [comment]
Agreed. there should also be a list of authors and contacts and license info etc... that's all planned for release 0.4

**Comment by egull** [comment]
done in current homepage, thanks to @gcarcassi
