### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by poboiko** [ALPSCore/ALPSCore#90]
Currently both ALPS and ALPSCore lacks proper documentation on its modules, just some tutorials which might not be enough to learn how to use it. I believe it is very important.
I can volunteer with that, but I might need some help since not everything inside ALPSCore is obvious for me.

**Comment by galexv** [comment]
(This is related to  #53 &mdash; maybe a duplicate?)
We decided to use Doxygen for documenting the API, and Sphinx (http://sphinx-doc.org/), which is based on reStructuredText (http://docutils.sourceforge.net/rst.html), for overview and higher-level instructions that are not captured by Doxygen and in-code comments. 

I would think a good place for the documentation would be `doc/` subdirectory with the structure mirroring the structure of the source directories: `doc/accumulators`, `doc/mc` and so on. Thoughts?

**Comment by egull** [comment]
Either works, no strong opinions.

**Comment by egull** [comment]
@poboiko a quick update for you for the next month: We have someone working with us to set up the documentation frontend on April 29, and he'll stay for a week. That's when a lot will be updated and documented. If you want to be involved in helping us write etc please let me know!

**Comment by poboiko** [comment]
@egull I do, but unfortunately from April 28th till May 3rd I will be unavailable (participating in a conference) :disappointed: 
Still I am willing to join after that.

**Comment by egull** [comment]
@poboiko have a look at what we've done so far (www.alpscore.org). We'll be working on this intensively for the next three days – feel free to join in!

**Comment by egull** [comment]
I'm closing this now. Not because we're done, but because we're a step further along. This is a neverending issue!
