### ISSUE TITLE
MC tutorial tries to read a wrong checkpoint file

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#92]
This is another issue that used to be #87 : MC tutorial (both 01-c++ and 02-mcbase versions) do not deduce the name of the checkpoint file correctly. When started as ./tutorial -c param.clone0.h5 the program tries to read from param.clone0.clone0.h5. There is a simple workaround (`ln -s param.clone0.h5 param.clone0.clone0.h5`), and anyway this is to go away in the updated tutorials that use the new parameters class.

**Comment by galexv** [comment]
Releases 0.3+ use the new parameter class and the tutorial code is updated. Resolving this issue would be a bugfix for 0.2.90, but is not pertinent for 0.4 &mdash; i am removing the milestone label.

**Comment by egull** [comment]
Is it still worth fixing this in 0.2.9 at all?

**Comment by galexv** [comment]
I think we should forget about it. Marking it as "wontfix" and closing...
