### ISSUE TITLE
0.3 rc1 does not compile under intel

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#93]
Intel has problems with the new parameter class. The failure seems to be here:

In file included from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params/option_type.hpp(41),
                 from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params.hpp(43),
                 from /Users/egull/ALPSCore/ALPSCore/params/src/params.cpp(24):
/opt/local/include/boost/mpl/aux_/push_back_impl.hpp(40): error: no instance of function template "boost::mpl::assertion_failed" matches the argument list
In file included from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params/option_type.hpp(41),
                 from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params.hpp(43),
                 from /Users/egull/ALPSCore/ALPSCore/params/src/params.cpp(24):
            argument types are: (boost::mpl::failed ************(boost::mpl::push_back_impl<boost::mpl::aux::vector_tag<20L>>::apply<boost::mpl::vector20<int, unsigned int, float, double, long double, long, unsigned long, long long, unsigned long long, char, signed char, unsigned char, short, unsigned short, bool, std::__1::string, std::__1::vector<signed int, std::__1::allocator<signed int>>, std::__1::vector<unsigned int, std::__1::allocator<unsigned int>>, std::__1::vector<float,
                      std::__1::allocator<float>>, std::__1::vector<double, std::__1::allocator<double>>>, std::__1::vector<long double, std::__1::allocator<long double>>>::REQUESTED_PUSH_BACK_SPECIALIZATION_FOR_SEQUENCE_DOES_NOT_EXIST::************)(boost::mpl::vector20<int, unsigned int, float, double, long double, long, unsigned long, long long, unsigned long long, char, signed char, unsigned char, short, unsigned short, bool, std::__1::string, std::__1::vector<signed int,
                      std::__1::allocator<signed int>>, std::__1::vector<unsigned int, std::__1::allocator<unsigned int>>, std::__1::vector<float, std::__1::allocator<float>>, std::__1::vector<double, std::__1::allocator<double>>>))
In file included from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params/option_type.hpp(41),
                 from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params.hpp(43),
                 from /Users/egull/ALPSCore/ALPSCore/params/src/params.cpp(24):
          BOOST_MPL_ASSERT_MSG(
          ^
In file included from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params/option_type.hpp(41),
                 from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params.hpp(43),
                 from /Users/egull/ALPSCore/ALPSCore/params/src/params.cpp(24):
          detected during:
In file included from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params/option_type.hpp(41),
                 from /Users/egull/ALPSCore/ALPSCore/params/include/alps/params.hpp(43),
                 from /Users/egull/ALPSCore/ALPSCore/params/src/params.cpp(24):
            instantiation of class "boost::mpl::push_back_impl<Tag>::apply<Sequence, T> [with Tag=boost::mpl::aux::vector_tag<20L>, Sequence=boost::mpl::vector20<int, unsigned int, float, double, long double, long, unsigned long, long long, unsigned long long, char, signed char, unsigned char, short, unsigned short, bool, std::__1::string, std::__1::vector<signed int, std::__1::allocator<signed int>>, std::__1::vector<unsigned int, std::__1::allocator<unsigned int>>, std::__1::vector<float,
                      std::__1::allocator<float>>, std::__1::vector<double, std::__1::allocator<double>>>, T=std::__1::vector<long double, std::__1::allocator<long double>>]" at line 30 of "/opt/local/include/boost/mpl/push_back.hpp"

**Comment by galexv** [comment]
Fixed by commit 492a366, and/or 812babe8.
