### ISSUE TITLE
Intel osx test failures

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#94]
icc (ICC) 15.0.1 20141022
Copyright (C) 1985-2014 Intel Corporation.  All rights reserved.

99% tests passed, 3 tests failed out of 336

openmpi-1.8.4

Total Test time (real) = 192.97 sec

The following tests FAILED:
	334 - sum_mpi (OTHER_FAULT)
	335 - reduce (OTHER_FAULT)
	336 - signed_obs (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8

**Comment by galexv** [comment]
@egull : could you send your `CMakeCache.txt` so i can reproduce the environment? Thanks!

**Comment by galexv** [comment]
Looks like duplicate of issue #86.

**Comment by egull** [comment]
Yep, let's close and fix #86.
