### ISSUE TITLE
Run Jenkins MPI tests in parallel

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#97]
It would be good to run MPI tests in parallel on Jenkins. Right now i see issues that show up only in parallel runs.

**Comment by egull** [comment]
With an on-premise executor we could probably  do that locally. I don't think we can do it on cloudbees.

**Comment by galexv** [comment]
The provision for MPI-run tests is introduced by commit a988a8a698. It seems to work on cloudbees, although once i saw an MPI test stuck (it could be internal cloudbees issue). I am closing this for now.
