### ISSUE TITLE
Option of linking tests with gtest or gtest_main

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#98]
Currently all tests seem to be linked with `libgtest_main`, which defines its own `main()`. In some cases, we need our own custom `main()`: especially in MPI tests, where it is necessary to set up and destroy MPI environment before/after running the tests. Strangely enough, tests with custom `main()` are compiled and linked successfully; however, they show odd behavior sometimes (like running tests *after* destroying MPI). We need an option of linking selected tests with `gtest` rather than `gtest_main`.

**Comment by egull** [comment]
An alternative place to put MPI_Init is in a test fixture:
https://code.google.com/p/googletest/wiki/FAQ#Should_I_use_the_constructor/destructor_of_the_test_fixture_or_t
...or in SetUP(). Have you thought about this? I think it boils down to knowing if we can call MPI_Init/MPI_Finalize multiple times (in which case we could have it in TEST_F) or if we can only do it once per program.

**Comment by galexv** [comment]
Yes, i thought about this.
AFAIK, it is not allowed call any MPI_* after MPI_Finalize() --- even MPI_Init().

**Comment by aeantipov** [comment]
I typically put mpi into "main" of tests. More or less like the answer here: http://stackoverflow.com/questions/16526664/unit-testing-mpi-programs-with-gtest

**Comment by galexv** [comment]
Exactly my point. That's why we need to be able to define our own `main()`, which is not possible if `libgtest_main.a` is linked.

**Comment by galexv** [comment]
The feature is introduced by commit 1e9c60bc.
